<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class HardSubjectQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [

            // ══════════════════════════════════════════════════════════════════
            // CHEMISTRY
            // ══════════════════════════════════════════════════════════════════

            // ── Chemistry - Element Symbols ──────────────────────────────────
            ['body' => 'What is the chemical symbol for Hydrogen?', 'correct_answer' => 'h', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Helium?', 'correct_answer' => 'he', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Lithium?', 'correct_answer' => 'li', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Carbon?', 'correct_answer' => 'c', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Nitrogen?', 'correct_answer' => 'n', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Oxygen?', 'correct_answer' => 'o', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Fluorine?', 'correct_answer' => 'f', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Neon?', 'correct_answer' => 'ne', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Sodium?', 'correct_answer' => 'na', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Magnesium?', 'correct_answer' => 'mg', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Aluminum?', 'correct_answer' => 'al', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Silicon?', 'correct_answer' => 'si', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Phosphorus?', 'correct_answer' => 'p', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Sulfur?', 'correct_answer' => 's', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Chlorine?', 'correct_answer' => 'cl', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Potassium?', 'correct_answer' => 'k', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Calcium?', 'correct_answer' => 'ca', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Iron?', 'correct_answer' => 'fe', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Copper?', 'correct_answer' => 'cu', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Zinc?', 'correct_answer' => 'zn', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Silver?', 'correct_answer' => 'ag', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Gold?', 'correct_answer' => 'au', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Mercury?', 'correct_answer' => 'hg', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Lead?', 'correct_answer' => 'pb', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Tin?', 'correct_answer' => 'sn', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Platinum?', 'correct_answer' => 'pt', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Iodine?', 'correct_answer' => 'i', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Bromine?', 'correct_answer' => 'br', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Nickel?', 'correct_answer' => 'ni', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical symbol for Tungsten?', 'correct_answer' => 'w', 'category' => 'Chemistry'],

            // ── Chemistry - Element Names from Symbol ────────────────────────
            ['body' => 'Which element has the chemical symbol "Na"?', 'correct_answer' => 'sodium', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "K"?', 'correct_answer' => 'potassium', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "Fe"?', 'correct_answer' => 'iron', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "Au"?', 'correct_answer' => 'gold', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "Ag"?', 'correct_answer' => 'silver', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "Pb"?', 'correct_answer' => 'lead', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "Sn"?', 'correct_answer' => 'tin', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "W"?', 'correct_answer' => 'tungsten', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "Hg"?', 'correct_answer' => 'mercury', 'category' => 'Chemistry'],
            ['body' => 'Which element has the chemical symbol "Sb"?', 'correct_answer' => 'antimony', 'category' => 'Chemistry'],

            // ── Chemistry - Atomic Numbers ────────────────────────────────────
            ['body' => 'What is the atomic number of Hydrogen?', 'correct_answer' => '1', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Carbon?', 'correct_answer' => '6', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Oxygen?', 'correct_answer' => '8', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Nitrogen?', 'correct_answer' => '7', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Iron?', 'correct_answer' => '26', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Gold?', 'correct_answer' => '79', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Helium?', 'correct_answer' => '2', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Sodium?', 'correct_answer' => '11', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Uranium?', 'correct_answer' => '92', 'category' => 'Chemistry'],
            ['body' => 'What is the atomic number of Calcium?', 'correct_answer' => '20', 'category' => 'Chemistry'],

            // ── Chemistry - Chemical Formulas ────────────────────────────────
            ['body' => 'What is the chemical formula for water?', 'correct_answer' => 'h2o', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for table salt?', 'correct_answer' => 'nacl', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for carbon dioxide?', 'correct_answer' => 'co2', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for methane?', 'correct_answer' => 'ch4', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for ammonia?', 'correct_answer' => 'nh3', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for glucose?', 'correct_answer' => 'c6h12o6', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for sulfuric acid?', 'correct_answer' => 'h2so4', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for hydrochloric acid?', 'correct_answer' => 'hcl', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for baking soda (sodium bicarbonate)?', 'correct_answer' => 'nahco3', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for ozone?', 'correct_answer' => 'o3', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for hydrogen peroxide?', 'correct_answer' => 'h2o2', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for nitric acid?', 'correct_answer' => 'hno3', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for ethanol?', 'correct_answer' => 'c2h5oh', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for carbon monoxide?', 'correct_answer' => 'co', 'category' => 'Chemistry'],
            ['body' => 'What is the chemical formula for calcium carbonate (limestone)?', 'correct_answer' => 'caco3', 'category' => 'Chemistry'],

            // ── Chemistry - Definitions & Concepts ───────────────────────────
            ['body' => 'What is the smallest unit of an element that still retains its properties called?', 'correct_answer' => 'atom', 'category' => 'Chemistry'],
            ['body' => 'What is the term for two or more atoms bonded together?', 'correct_answer' => 'molecule', 'category' => 'Chemistry'],
            ['body' => 'What is an atom called after it has gained or lost electrons?', 'correct_answer' => 'ion', 'category' => 'Chemistry'],
            ['body' => 'What are atoms of the same element with different numbers of neutrons called?', 'correct_answer' => 'isotope', 'category' => 'Chemistry'],
            ['body' => 'What is the SI base unit for the amount of a substance?', 'correct_answer' => 'mole', 'category' => 'Chemistry'],
            ['body' => 'What is a substance called that speeds up a chemical reaction without being consumed?', 'correct_answer' => 'catalyst', 'category' => 'Chemistry'],
            ['body' => 'What is the name of the positively charged subatomic particle found in the nucleus?', 'correct_answer' => 'proton', 'category' => 'Chemistry'],
            ['body' => 'What is the name of the negatively charged subatomic particle that orbits the nucleus?', 'correct_answer' => 'electron', 'category' => 'Chemistry'],
            ['body' => 'What is the name of the subatomic particle with no electrical charge found in the nucleus?', 'correct_answer' => 'neutron', 'category' => 'Chemistry'],
            ['body' => 'What pH value indicates a neutral solution?', 'correct_answer' => '7', 'category' => 'Chemistry'],
            ['body' => 'What term describes the electrons in the outermost shell of an atom that are involved in bonding?', 'correct_answer' => 'valence electrons', 'category' => 'Chemistry'],
            ['body' => 'What type of chemical bond is formed by atoms sharing electron pairs?', 'correct_answer' => 'covalent bond', 'category' => 'Chemistry'],
            ['body' => 'What type of chemical bond is formed by the transfer of electrons between atoms?', 'correct_answer' => 'ionic bond', 'category' => 'Chemistry'],
            ['body' => 'What is the approximate value of Avogadro\'s number, in particles per mole?', 'correct_answer' => '6.022 x 10^23', 'category' => 'Chemistry'],
            ['body' => 'What is the general term for a chemical reaction where a substance reacts with oxygen, often releasing heat and light?', 'correct_answer' => 'combustion', 'category' => 'Chemistry'],
            ['body' => 'According to the Bronsted-Lowry definition, what do we call a substance that donates protons in a reaction?', 'correct_answer' => 'acid', 'category' => 'Chemistry'],
            ['body' => 'According to the Bronsted-Lowry definition, what do we call a substance that accepts protons in a reaction?', 'correct_answer' => 'base', 'category' => 'Chemistry'],
            ['body' => 'What is the term for a mixture where one substance is dissolved uniformly throughout another?', 'correct_answer' => 'solution', 'category' => 'Chemistry'],
            ['body' => 'What is the term for the minimum energy required to start a chemical reaction?', 'correct_answer' => 'activation energy', 'category' => 'Chemistry'],
            ['body' => 'What law states that matter cannot be created or destroyed in a chemical reaction?', 'correct_answer' => 'law of conservation of mass', 'category' => 'Chemistry'],

            // ── Chemistry - Famous Chemists ───────────────────────────────────
            ['body' => 'Which scientist created the first widely recognized periodic table of elements?', 'correct_answer' => 'dmitri mendeleev', 'category' => 'Chemistry'],
            ['body' => 'Which scientist is known as the father of modern chemistry for formulating the law of conservation of mass?', 'correct_answer' => 'antoine lavoisier', 'category' => 'Chemistry'],
            ['body' => 'Which scientist discovered radioactivity and won Nobel Prizes in two different sciences?', 'correct_answer' => 'marie curie', 'category' => 'Chemistry'],
            ['body' => 'Which scientist proposed that atoms of different elements combine in simple whole number ratios?', 'correct_answer' => 'john dalton', 'category' => 'Chemistry'],
            ['body' => 'Which chemist developed the concept of pH?', 'correct_answer' => 'soren sorensen', 'category' => 'Chemistry'],
            ['body' => 'Which scientist is credited with discovering the electron?', 'correct_answer' => 'j.j. thomson', 'category' => 'Chemistry'],
            ['body' => 'Which scientist proposed the nuclear model of the atom, with a dense positive nucleus?', 'correct_answer' => 'ernest rutherford', 'category' => 'Chemistry'],
            ['body' => 'Which scientist developed the model of the atom with electrons orbiting in defined energy levels?', 'correct_answer' => 'niels bohr', 'category' => 'Chemistry'],
            ['body' => 'Which scientist is credited with discovering the neutron?', 'correct_answer' => 'james chadwick', 'category' => 'Chemistry'],
            ['body' => 'What law states that the pressure and volume of a gas are inversely proportional at constant temperature?', 'correct_answer' => 'boyles law', 'category' => 'Chemistry'],

            // ── Chemistry - Phase Changes ─────────────────────────────────────
            ['body' => 'What is the change of state from liquid to gas called?', 'correct_answer' => 'vaporization', 'category' => 'Chemistry'],
            ['body' => 'What is the change of state from gas directly to solid called?', 'correct_answer' => 'deposition', 'category' => 'Chemistry'],
            ['body' => 'What is the change of state from solid directly to gas called?', 'correct_answer' => 'sublimation', 'category' => 'Chemistry'],
            ['body' => 'What is the change of state from liquid to solid called?', 'correct_answer' => 'freezing', 'category' => 'Chemistry'],
            ['body' => 'What is the change of state from gas to liquid called?', 'correct_answer' => 'condensation', 'category' => 'Chemistry'],

            // ══════════════════════════════════════════════════════════════════
            // SCIENCE
            // ══════════════════════════════════════════════════════════════════

            // ── Science - Physics Fundamentals ───────────────────────────────
            ['body' => 'Which scientist formulated the three laws of motion?', 'correct_answer' => 'isaac newton', 'category' => 'Science'],
            ['body' => 'Newton\'s first law of motion is also known as the law of what?', 'correct_answer' => 'inertia', 'category' => 'Science'],
            ['body' => 'What is the formula relating force, mass, and acceleration?', 'correct_answer' => 'f=ma', 'category' => 'Science'],
            ['body' => 'What is the SI unit of force?', 'correct_answer' => 'newton', 'category' => 'Science'],
            ['body' => 'What is the SI unit of energy?', 'correct_answer' => 'joule', 'category' => 'Science'],
            ['body' => 'What is the SI unit of power?', 'correct_answer' => 'watt', 'category' => 'Science'],
            ['body' => 'What is the SI unit of electric current?', 'correct_answer' => 'ampere', 'category' => 'Science'],
            ['body' => 'What is the SI unit of electrical resistance?', 'correct_answer' => 'ohm', 'category' => 'Science'],
            ['body' => 'What is the SI unit of pressure?', 'correct_answer' => 'pascal', 'category' => 'Science'],
            ['body' => 'What is the SI unit of frequency?', 'correct_answer' => 'hertz', 'category' => 'Science'],
            ['body' => 'What physical quantity does "mph" measure?', 'correct_answer' => 'speed', 'category' => 'Science'],
            ['body' => 'What is the approximate speed of light in a vacuum, in kilometers per second?', 'correct_answer' => '300000 km/s', 'category' => 'Science'],
            ['body' => 'Which scientist developed the theory of general relativity?', 'correct_answer' => 'albert einstein', 'category' => 'Science'],
            ['body' => 'What is the famous equation relating energy and mass developed by Einstein?', 'correct_answer' => 'e=mc^2', 'category' => 'Science'],
            ['body' => 'What force pulls objects toward the center of the Earth?', 'correct_answer' => 'gravity', 'category' => 'Science'],
            ['body' => 'Which scientist is credited with discovering the law of universal gravitation after observing a falling apple?', 'correct_answer' => 'isaac newton', 'category' => 'Science'],
            ['body' => 'What is the term for the resistance of an object to a change in its motion?', 'correct_answer' => 'inertia', 'category' => 'Science'],
            ['body' => 'What is the term for the rate of change of velocity?', 'correct_answer' => 'acceleration', 'category' => 'Science'],
            ['body' => 'What is the term for the energy an object has due to its motion?', 'correct_answer' => 'kinetic energy', 'category' => 'Science'],
            ['body' => 'What is the term for the stored energy an object has due to its position?', 'correct_answer' => 'potential energy', 'category' => 'Science'],
            ['body' => 'What law states that energy cannot be created or destroyed, only transformed?', 'correct_answer' => 'law of conservation of energy', 'category' => 'Science'],
            ['body' => 'What type of simple machine is a see-saw an example of?', 'correct_answer' => 'lever', 'category' => 'Science'],
            ['body' => 'What is the term for a material that allows electricity to flow through it easily?', 'correct_answer' => 'conductor', 'category' => 'Science'],
            ['body' => 'What is the term for a material that resists the flow of electricity?', 'correct_answer' => 'insulator', 'category' => 'Science'],
            ['body' => 'What are the three most commonly discussed states of matter in school science?', 'correct_answer' => 'solid, liquid, gas', 'category' => 'Science'],

            // ── Science - Earth Science ───────────────────────────────────────
            ['body' => 'What is the name of the outermost solid layer of the Earth that we live on?', 'correct_answer' => 'crust', 'category' => 'Science'],
            ['body' => 'What is the name of the layer of the Earth directly beneath the crust, made of hot semi-solid rock?', 'correct_answer' => 'mantle', 'category' => 'Science'],
            ['body' => 'What is the name of the layer at the very center of the Earth, believed to be solid?', 'correct_answer' => 'inner core', 'category' => 'Science'],
            ['body' => 'What is the name of the layer surrounding the inner core, believed to be liquid metal?', 'correct_answer' => 'outer core', 'category' => 'Science'],
            ['body' => 'What theory explains that Earth\'s continents were once joined and have since drifted apart?', 'correct_answer' => 'plate tectonics', 'category' => 'Science'],
            ['body' => 'What is the natural process by which water moves through evaporation, condensation, and precipitation called?', 'correct_answer' => 'water cycle', 'category' => 'Science'],
            ['body' => 'What is a sudden release of energy in the Earth\'s crust that creates seismic waves called?', 'correct_answer' => 'earthquake', 'category' => 'Science'],
            ['body' => 'What is a mountain that can erupt, releasing lava, ash, and gases, called?', 'correct_answer' => 'volcano', 'category' => 'Science'],
            ['body' => 'What instrument is used to measure the vibrations of an earthquake?', 'correct_answer' => 'seismograph', 'category' => 'Science'],
            ['body' => 'What type of rock is formed from cooled magma or lava?', 'correct_answer' => 'igneous rock', 'category' => 'Science'],
            ['body' => 'What type of rock is formed from compressed layers of sediment?', 'correct_answer' => 'sedimentary rock', 'category' => 'Science'],
            ['body' => 'What type of rock is changed by heat and pressure?', 'correct_answer' => 'metamorphic rock', 'category' => 'Science'],
            ['body' => 'What is the layer of gases surrounding the Earth called?', 'correct_answer' => 'atmosphere', 'category' => 'Science'],
            ['body' => 'What gas makes up about 78 percent of Earth\'s atmosphere?', 'correct_answer' => 'nitrogen', 'category' => 'Science'],
            ['body' => 'What gas makes up about 21 percent of Earth\'s atmosphere?', 'correct_answer' => 'oxygen', 'category' => 'Science'],
            ['body' => 'What is the study of weather and atmospheric conditions called?', 'correct_answer' => 'meteorology', 'category' => 'Science'],
            ['body' => 'What is the term for a large, slow-moving mass of ice?', 'correct_answer' => 'glacier', 'category' => 'Science'],
            ['body' => 'What is the term for the boundary where two tectonic plates meet?', 'correct_answer' => 'fault line', 'category' => 'Science'],
            ['body' => 'What is the term for the process by which rock is broken down and worn away over time?', 'correct_answer' => 'erosion', 'category' => 'Science'],
            ['body' => 'What is the layer of the atmosphere closest to Earth\'s surface, where weather occurs, called?', 'correct_answer' => 'troposphere', 'category' => 'Science'],
            ['body' => 'The ozone layer is found in which layer of the atmosphere?', 'correct_answer' => 'stratosphere', 'category' => 'Science'],
            ['body' => 'What scale is used to measure the strength of hurricanes?', 'correct_answer' => 'saffir-simpson scale', 'category' => 'Science'],
            ['body' => 'What is the term for a large wave caused by underwater earthquakes or volcanic activity?', 'correct_answer' => 'tsunami', 'category' => 'Science'],
            ['body' => 'What is the term for the imaginary line around the middle of the Earth?', 'correct_answer' => 'equator', 'category' => 'Science'],
            ['body' => 'What is the study of rocks and minerals called?', 'correct_answer' => 'geology', 'category' => 'Science'],

            // ── Science - Astronomy ───────────────────────────────────────────
            ['body' => 'What star is at the center of our solar system?', 'correct_answer' => 'the sun', 'category' => 'Science'],
            ['body' => 'What is the closest planet to the sun?', 'correct_answer' => 'mercury', 'category' => 'Science'],
            ['body' => 'What is the largest planet in our solar system?', 'correct_answer' => 'jupiter', 'category' => 'Science'],
            ['body' => 'What is the smallest planet in our solar system?', 'correct_answer' => 'mercury', 'category' => 'Science'],
            ['body' => 'Which planet is known for its prominent ring system?', 'correct_answer' => 'saturn', 'category' => 'Science'],
            ['body' => 'Which planet is known as the Red Planet and is fourth from the sun?', 'correct_answer' => 'mars', 'category' => 'Science'],
            ['body' => 'What is the only planet known to support life?', 'correct_answer' => 'earth', 'category' => 'Science'],
            ['body' => 'What natural satellite orbits the Earth?', 'correct_answer' => 'the moon', 'category' => 'Science'],
            ['body' => 'What is a large collection of stars, gas, and dust bound together by gravity called?', 'correct_answer' => 'galaxy', 'category' => 'Science'],
            ['body' => 'What is the name of the galaxy that contains our solar system?', 'correct_answer' => 'the milky way', 'category' => 'Science'],
            ['body' => 'What is the term for the path an object takes as it circles another object in space?', 'correct_answer' => 'orbit', 'category' => 'Science'],
            ['body' => 'How long does it take Earth to complete one full rotation on its axis?', 'correct_answer' => '24 hours', 'category' => 'Science'],
            ['body' => 'How long does it take Earth to complete one full orbit around the sun?', 'correct_answer' => '365 days', 'category' => 'Science'],
            ['body' => 'What is a small rocky object that orbits the sun, often found in a belt between Mars and Jupiter, called?', 'correct_answer' => 'asteroid', 'category' => 'Science'],
            ['body' => 'What is a small icy body that develops a glowing tail as it nears the sun called?', 'correct_answer' => 'comet', 'category' => 'Science'],
            ['body' => 'What is the explosive death of a massive star called?', 'correct_answer' => 'supernova', 'category' => 'Science'],
            ['body' => 'What is an extremely dense region of space where gravity is so strong not even light can escape called?', 'correct_answer' => 'black hole', 'category' => 'Science'],
            ['body' => 'What is a celestial body that generates its own light and heat through nuclear fusion called?', 'correct_answer' => 'star', 'category' => 'Science'],
            ['body' => 'Which planet is known as Earth\'s twin due to its similar size?', 'correct_answer' => 'venus', 'category' => 'Science'],
            ['body' => 'What is the event called when the moon passes between the Earth and the sun, blocking sunlight?', 'correct_answer' => 'solar eclipse', 'category' => 'Science'],
            ['body' => 'What is the event called when the Earth passes between the sun and the moon, casting a shadow on the moon?', 'correct_answer' => 'lunar eclipse', 'category' => 'Science'],
            ['body' => 'Which former planet was reclassified as a dwarf planet in 2006?', 'correct_answer' => 'pluto', 'category' => 'Science'],
            ['body' => 'What is the name of the space agency that led the Apollo moon landing missions?', 'correct_answer' => 'nasa', 'category' => 'Science'],
            ['body' => 'Who was the first person to walk on the moon?', 'correct_answer' => 'neil armstrong', 'category' => 'Science'],
            ['body' => 'What is the study of celestial objects and the universe called?', 'correct_answer' => 'astronomy', 'category' => 'Science'],

            // ── Science - Scientific Method & General Science ────────────────
            ['body' => 'What is an educated guess or testable prediction in an experiment called?', 'correct_answer' => 'hypothesis', 'category' => 'Science'],
            ['body' => 'What is a well-substantiated explanation acquired through the scientific method called?', 'correct_answer' => 'theory', 'category' => 'Science'],
            ['body' => 'What is the factor that is deliberately changed in an experiment called?', 'correct_answer' => 'independent variable', 'category' => 'Science'],
            ['body' => 'What is the factor that is measured or observed as a result in an experiment called?', 'correct_answer' => 'dependent variable', 'category' => 'Science'],
            ['body' => 'What is a factor kept the same throughout an experiment to ensure a fair test called?', 'correct_answer' => 'control variable', 'category' => 'Science'],
            ['body' => 'What is a description that is well-tested and consistently observed, but doesn\'t explain why, called?', 'correct_answer' => 'scientific law', 'category' => 'Science'],
            ['body' => 'What is the smallest unit that living organisms are made of?', 'correct_answer' => 'cell', 'category' => 'Science'],
            ['body' => 'What system of measurement is used internationally in science?', 'correct_answer' => 'metric system', 'category' => 'Science'],
            ['body' => 'What is the boiling point of water in Celsius at sea level?', 'correct_answer' => '100 degrees celsius', 'category' => 'Science'],
            ['body' => 'What is the freezing point of water in Celsius?', 'correct_answer' => '0 degrees celsius', 'category' => 'Science'],
            ['body' => 'What is the term for the amount of matter in an object?', 'correct_answer' => 'mass', 'category' => 'Science'],
            ['body' => 'What is the term for the force of gravity acting on an object\'s mass?', 'correct_answer' => 'weight', 'category' => 'Science'],
            ['body' => 'What is the term for the amount of space an object occupies?', 'correct_answer' => 'volume', 'category' => 'Science'],
            ['body' => 'What is the term for mass per unit volume of a substance?', 'correct_answer' => 'density', 'category' => 'Science'],
            ['body' => 'What is the term for energy that travels in waves and can be seen by the human eye?', 'correct_answer' => 'visible light', 'category' => 'Science'],
            ['body' => 'What is a substance made of two or more elements chemically combined called?', 'correct_answer' => 'compound', 'category' => 'Science'],
            ['body' => 'What is the transfer of heat through direct contact called?', 'correct_answer' => 'conduction', 'category' => 'Science'],
            ['body' => 'What is the transfer of heat through fluid movement called?', 'correct_answer' => 'convection', 'category' => 'Science'],
            ['body' => 'What is the transfer of heat through electromagnetic waves, without needing matter, called?', 'correct_answer' => 'radiation', 'category' => 'Science'],
            ['body' => 'What is the bending of light as it passes from one medium to another called?', 'correct_answer' => 'refraction', 'category' => 'Science'],
            ['body' => 'What is light bouncing off a surface called?', 'correct_answer' => 'reflection', 'category' => 'Science'],
            ['body' => 'What is the number of wave cycles that pass a point per second called?', 'correct_answer' => 'frequency', 'category' => 'Science'],
            ['body' => 'What is the distance between two successive crests of a wave called?', 'correct_answer' => 'wavelength', 'category' => 'Science'],
            ['body' => 'What is the term for sound waves with a frequency too high for humans to hear?', 'correct_answer' => 'ultrasound', 'category' => 'Science'],
            ['body' => 'What is the branch of science that studies matter, energy, and their interactions called?', 'correct_answer' => 'physics', 'category' => 'Science'],

            // ══════════════════════════════════════════════════════════════════
            // BIOLOGY
            // ══════════════════════════════════════════════════════════════════

            // ── Biology - Cell Biology ────────────────────────────────────────
            ['body' => 'What organelle is known as the powerhouse of the cell?', 'correct_answer' => 'mitochondria', 'category' => 'Biology'],
            ['body' => 'What organelle controls the cell\'s activities and contains its DNA?', 'correct_answer' => 'nucleus', 'category' => 'Biology'],
            ['body' => 'What organelle is responsible for synthesizing proteins in a cell?', 'correct_answer' => 'ribosome', 'category' => 'Biology'],
            ['body' => 'What organelle in plant cells carries out photosynthesis?', 'correct_answer' => 'chloroplast', 'category' => 'Biology'],
            ['body' => 'What rigid outer layer is found in plant cells but not animal cells?', 'correct_answer' => 'cell wall', 'category' => 'Biology'],
            ['body' => 'What structure regulates what enters and exits the cell?', 'correct_answer' => 'cell membrane', 'category' => 'Biology'],
            ['body' => 'What is the jelly-like substance filling the cell, where organelles are suspended, called?', 'correct_answer' => 'cytoplasm', 'category' => 'Biology'],
            ['body' => 'What organelle packages and ships proteins, often called the "post office" of the cell?', 'correct_answer' => 'golgi apparatus', 'category' => 'Biology'],
            ['body' => 'What organelle breaks down waste and cellular debris?', 'correct_answer' => 'lysosome', 'category' => 'Biology'],
            ['body' => 'What network of membranes is involved in protein and lipid synthesis within a cell?', 'correct_answer' => 'endoplasmic reticulum', 'category' => 'Biology'],
            ['body' => 'What fluid-filled sac is used for storage in plant cells?', 'correct_answer' => 'vacuole', 'category' => 'Biology'],
            ['body' => 'What is the basic unit of life called?', 'correct_answer' => 'cell', 'category' => 'Biology'],
            ['body' => 'What term describes a cell that has no true, membrane-bound nucleus?', 'correct_answer' => 'prokaryote', 'category' => 'Biology'],
            ['body' => 'What term describes a cell that has a true, membrane-bound nucleus?', 'correct_answer' => 'eukaryote', 'category' => 'Biology'],
            ['body' => 'What is the process by which a single cell divides into two identical daughter cells called?', 'correct_answer' => 'mitosis', 'category' => 'Biology'],

            // ── Biology - Genetics ────────────────────────────────────────────
            ['body' => 'What molecule carries genetic information in living organisms?', 'correct_answer' => 'dna', 'category' => 'Biology'],
            ['body' => 'What molecule helps translate genetic code into proteins?', 'correct_answer' => 'rna', 'category' => 'Biology'],
            ['body' => 'What is the basic unit of heredity called?', 'correct_answer' => 'gene', 'category' => 'Biology'],
            ['body' => 'What structure, made of coiled DNA, carries genetic information in a cell?', 'correct_answer' => 'chromosome', 'category' => 'Biology'],
            ['body' => 'How many chromosomes are in a normal human cell?', 'correct_answer' => '46', 'category' => 'Biology'],
            ['body' => 'Which scientist is known as the father of modern genetics for his pea plant experiments?', 'correct_answer' => 'gregor mendel', 'category' => 'Biology'],
            ['body' => 'Which two scientists are credited with discovering the double helix structure of DNA?', 'correct_answer' => 'watson and crick', 'category' => 'Biology'],
            ['body' => 'What term describes an organism\'s observable physical traits?', 'correct_answer' => 'phenotype', 'category' => 'Biology'],
            ['body' => 'What term describes an organism\'s genetic makeup?', 'correct_answer' => 'genotype', 'category' => 'Biology'],
            ['body' => 'What is an alternative form of a gene called?', 'correct_answer' => 'allele', 'category' => 'Biology'],
            ['body' => 'What type of cell division produces sex cells with half the normal chromosome number?', 'correct_answer' => 'meiosis', 'category' => 'Biology'],
            ['body' => 'What term describes a trait that is expressed even when only one copy of the allele is present?', 'correct_answer' => 'dominant trait', 'category' => 'Biology'],
            ['body' => 'What term describes a trait that is only expressed when two copies of the allele are present?', 'correct_answer' => 'recessive trait', 'category' => 'Biology'],
            ['body' => 'What is the process by which a DNA sequence is copied into RNA called?', 'correct_answer' => 'transcription', 'category' => 'Biology'],
            ['body' => 'What is the process by which RNA is used to build a protein called?', 'correct_answer' => 'translation', 'category' => 'Biology'],

            // ── Biology - Human Anatomy & Physiology ──────────────────────────
            ['body' => 'What organ pumps blood throughout the human body?', 'correct_answer' => 'heart', 'category' => 'Biology'],
            ['body' => 'What organ filters waste from the blood to produce urine?', 'correct_answer' => 'kidney', 'category' => 'Biology'],
            ['body' => 'What organ produces bile and detoxifies chemicals in the body?', 'correct_answer' => 'liver', 'category' => 'Biology'],
            ['body' => 'What organs perform gas exchange with the air we breathe?', 'correct_answer' => 'lungs', 'category' => 'Biology'],
            ['body' => 'What is the largest organ of the human body?', 'correct_answer' => 'skin', 'category' => 'Biology'],
            ['body' => 'What organ system, made of muscles, is responsible for movement?', 'correct_answer' => 'muscular system', 'category' => 'Biology'],
            ['body' => 'What organ system, made up of bones, supports and protects the body?', 'correct_answer' => 'skeletal system', 'category' => 'Biology'],
            ['body' => 'How many bones are in the adult human body?', 'correct_answer' => '206', 'category' => 'Biology'],
            ['body' => 'What organ controls the nervous system and serves as the center of thought?', 'correct_answer' => 'brain', 'category' => 'Biology'],
            ['body' => 'What muscle separates the chest cavity from the abdominal cavity and aids breathing?', 'correct_answer' => 'diaphragm', 'category' => 'Biology'],
            ['body' => 'What fluid tissue transports oxygen and nutrients throughout the human body?', 'correct_answer' => 'blood', 'category' => 'Biology'],
            ['body' => 'What gland in the neck regulates metabolism by producing hormones?', 'correct_answer' => 'thyroid gland', 'category' => 'Biology'],
            ['body' => 'What part of the brain is responsible for balance and coordination?', 'correct_answer' => 'cerebellum', 'category' => 'Biology'],
            ['body' => 'What part of the brain is responsible for higher thought and voluntary movement?', 'correct_answer' => 'cerebrum', 'category' => 'Biology'],
            ['body' => 'What organ digests food using acid, located in the abdomen?', 'correct_answer' => 'stomach', 'category' => 'Biology'],
            ['body' => 'What is the primary function of the small intestine?', 'correct_answer' => 'nutrient absorption', 'category' => 'Biology'],
            ['body' => 'What blood cells are responsible for carrying oxygen throughout the body?', 'correct_answer' => 'red blood cells', 'category' => 'Biology'],
            ['body' => 'What blood cells are responsible for fighting infection?', 'correct_answer' => 'white blood cells', 'category' => 'Biology'],
            ['body' => 'What cell fragments in the blood are responsible for clotting?', 'correct_answer' => 'platelets', 'category' => 'Biology'],
            ['body' => 'How many chambers does the human heart have?', 'correct_answer' => '4', 'category' => 'Biology'],

            // ── Biology - Taxonomy & Evolution ────────────────────────────────
            ['body' => 'Which scientist is known as the father of the theory of evolution by natural selection?', 'correct_answer' => 'charles darwin', 'category' => 'Biology'],
            ['body' => 'What is the process called where species change over generations due to differential survival and reproduction?', 'correct_answer' => 'natural selection', 'category' => 'Biology'],
            ['body' => 'In the classification hierarchy, what taxonomic rank comes directly after "kingdom"?', 'correct_answer' => 'phylum', 'category' => 'Biology'],
            ['body' => 'What is the two-part naming system for species, using genus and species, called?', 'correct_answer' => 'binomial nomenclature', 'category' => 'Biology'],
            ['body' => 'What term describes organisms that share a common ancestor?', 'correct_answer' => 'common descent', 'category' => 'Biology'],
            ['body' => 'What is the broadest classification level in modern taxonomy, ranked above kingdom?', 'correct_answer' => 'domain', 'category' => 'Biology'],
            ['body' => 'What kingdom includes multicellular organisms that perform photosynthesis?', 'correct_answer' => 'plantae', 'category' => 'Biology'],
            ['body' => 'What kingdom includes multicellular organisms that consume other organisms for food?', 'correct_answer' => 'animalia', 'category' => 'Biology'],
            ['body' => 'What term describes a species that no longer exists?', 'correct_answer' => 'extinct', 'category' => 'Biology'],
            ['body' => 'What term describes structures in different species that share a common origin, like a human arm and a bat wing?', 'correct_answer' => 'homologous structures', 'category' => 'Biology'],

            // ── Biology - Ecology ─────────────────────────────────────────────
            ['body' => 'What term describes organisms that produce their own food using sunlight?', 'correct_answer' => 'producers', 'category' => 'Biology'],
            ['body' => 'What term describes organisms that eat other organisms for energy?', 'correct_answer' => 'consumers', 'category' => 'Biology'],
            ['body' => 'What term describes organisms that break down dead matter and recycle nutrients?', 'correct_answer' => 'decomposers', 'category' => 'Biology'],
            ['body' => 'What is the flow of energy through a series of organisms, each eating the one before, called?', 'correct_answer' => 'food chain', 'category' => 'Biology'],
            ['body' => 'What is the term for a network of interconnected food chains in an ecosystem?', 'correct_answer' => 'food web', 'category' => 'Biology'],
            ['body' => 'What term describes all the living and nonliving things in an area that interact with each other?', 'correct_answer' => 'ecosystem', 'category' => 'Biology'],
            ['body' => 'What process do plants use to convert sunlight, water, and carbon dioxide into glucose and oxygen?', 'correct_answer' => 'photosynthesis', 'category' => 'Biology'],
            ['body' => 'What process do cells use to break down glucose and release energy?', 'correct_answer' => 'cellular respiration', 'category' => 'Biology'],
            ['body' => 'What is a large area characterized by its climate and dominant plant and animal life called?', 'correct_answer' => 'biome', 'category' => 'Biology'],
            ['body' => 'What term describes the variety of life found in an ecosystem?', 'correct_answer' => 'biodiversity', 'category' => 'Biology'],

            // ── Biology - Plant Biology & Microbiology ────────────────────────
            ['body' => 'What plant tissue transports water from the roots to the leaves?', 'correct_answer' => 'xylem', 'category' => 'Biology'],
            ['body' => 'What plant tissue transports sugars produced by photosynthesis?', 'correct_answer' => 'phloem', 'category' => 'Biology'],
            ['body' => 'What are the small pores on leaves that allow gas exchange called?', 'correct_answer' => 'stomata', 'category' => 'Biology'],
            ['body' => 'What green pigment in plants absorbs sunlight for photosynthesis?', 'correct_answer' => 'chlorophyll', 'category' => 'Biology'],
            ['body' => 'What is the male reproductive part of a flower called?', 'correct_answer' => 'stamen', 'category' => 'Biology'],
            ['body' => 'What is the female reproductive part of a flower called?', 'correct_answer' => 'pistil', 'category' => 'Biology'],
            ['body' => 'What is the process by which pollen is transferred to fertilize a plant called?', 'correct_answer' => 'pollination', 'category' => 'Biology'],
            ['body' => 'What are single-celled microorganisms that lack a nucleus called?', 'correct_answer' => 'bacteria', 'category' => 'Biology'],
            ['body' => 'What are microscopic infectious agents that require a host cell to replicate called?', 'correct_answer' => 'virus', 'category' => 'Biology'],
            ['body' => 'What kingdom includes yeast, mold, and mushrooms?', 'correct_answer' => 'fungi', 'category' => 'Biology'],
            ['body' => 'What is the process by which bacteria reproduce by splitting into two called?', 'correct_answer' => 'binary fission', 'category' => 'Biology'],
            ['body' => 'What term describes a substance that kills or inhibits the growth of bacteria?', 'correct_answer' => 'antibiotic', 'category' => 'Biology'],
            ['body' => 'What is a weakened or dead pathogen used to trigger immunity called?', 'correct_answer' => 'vaccine', 'category' => 'Biology'],
            ['body' => 'What is the symbiotic relationship called where both organisms involved benefit?', 'correct_answer' => 'mutualism', 'category' => 'Biology'],
            ['body' => 'What is the symbiotic relationship called where one organism benefits and the other is harmed?', 'correct_answer' => 'parasitism', 'category' => 'Biology'],

            // ── Biology - Famous Biologists & General Terms ───────────────────
            ['body' => 'Which scientist first observed and named "cells" while using a microscope?', 'correct_answer' => 'robert hooke', 'category' => 'Biology'],
            ['body' => 'Which scientist discovered penicillin?', 'correct_answer' => 'alexander fleming', 'category' => 'Biology'],
            ['body' => 'Which naturalist developed the theory of evolution independently around the same time as Darwin?', 'correct_answer' => 'alfred russel wallace', 'category' => 'Biology'],
            ['body' => 'Which scientist is known for pioneering vaccination with the smallpox vaccine?', 'correct_answer' => 'edward jenner', 'category' => 'Biology'],
            ['body' => 'Louis Pasteur is best known for developing what food safety process?', 'correct_answer' => 'pasteurization', 'category' => 'Biology'],
            ['body' => 'What is the term for an organism\'s habitat plus its functional role within that habitat?', 'correct_answer' => 'ecological niche', 'category' => 'Biology'],
            ['body' => 'What term describes animals that are active mainly at night?', 'correct_answer' => 'nocturnal', 'category' => 'Biology'],
            ['body' => 'What term describes animals that maintain a constant internal body temperature?', 'correct_answer' => 'warm blooded', 'category' => 'Biology'],
            ['body' => 'What term describes animals whose body temperature depends on their environment?', 'correct_answer' => 'cold blooded', 'category' => 'Biology'],
            ['body' => 'What is the study of living organisms called?', 'correct_answer' => 'biology', 'category' => 'Biology'],
            ['body' => 'What is the study of heredity and genes called?', 'correct_answer' => 'genetics', 'category' => 'Biology'],
            ['body' => 'What is the study of animals called?', 'correct_answer' => 'zoology', 'category' => 'Biology'],
            ['body' => 'What is the study of plants called?', 'correct_answer' => 'botany', 'category' => 'Biology'],
            ['body' => 'What is the term for the process by which organisms maintain a stable internal environment?', 'correct_answer' => 'homeostasis', 'category' => 'Biology'],
            ['body' => 'What gas do plants absorb from the atmosphere during photosynthesis?', 'correct_answer' => 'carbon dioxide', 'category' => 'Biology'],

            // ══════════════════════════════════════════════════════════════════
            // CALCULUS
            // ══════════════════════════════════════════════════════════════════

            // ── Calculus - Power Rule Derivatives ─────────────────────────────
            ['body' => 'What is the derivative of x^2 with respect to x?', 'correct_answer' => '2x', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^3 with respect to x?', 'correct_answer' => '3x^2', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^4 with respect to x?', 'correct_answer' => '4x^3', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^5 with respect to x?', 'correct_answer' => '5x^4', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^6 with respect to x?', 'correct_answer' => '6x^5', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^7 with respect to x?', 'correct_answer' => '7x^6', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^8 with respect to x?', 'correct_answer' => '8x^7', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^9 with respect to x?', 'correct_answer' => '9x^8', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^10 with respect to x?', 'correct_answer' => '10x^9', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^11 with respect to x?', 'correct_answer' => '11x^10', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^12 with respect to x?', 'correct_answer' => '12x^11', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^13 with respect to x?', 'correct_answer' => '13x^12', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^14 with respect to x?', 'correct_answer' => '14x^13', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^15 with respect to x?', 'correct_answer' => '15x^14', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^16 with respect to x?', 'correct_answer' => '16x^15', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^20 with respect to x?', 'correct_answer' => '20x^19', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^25 with respect to x?', 'correct_answer' => '25x^24', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^30 with respect to x?', 'correct_answer' => '30x^29', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^50 with respect to x?', 'correct_answer' => '50x^49', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of x^100 with respect to x?', 'correct_answer' => '100x^99', 'category' => 'Calculus'],

            // ── Calculus - Derivatives with Coefficients ──────────────────────
            ['body' => 'What is the derivative of 3x^2 with respect to x?', 'correct_answer' => '6x', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 5x^3 with respect to x?', 'correct_answer' => '15x^2', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 4x^4 with respect to x?', 'correct_answer' => '16x^3', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 2x^5 with respect to x?', 'correct_answer' => '10x^4', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 7x^2 with respect to x?', 'correct_answer' => '14x', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 6x^3 with respect to x?', 'correct_answer' => '18x^2', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 10x with respect to x?', 'correct_answer' => '10', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 8x^4 with respect to x?', 'correct_answer' => '32x^3', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 9x^2 with respect to x?', 'correct_answer' => '18x', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 2x^6 with respect to x?', 'correct_answer' => '12x^5', 'category' => 'Calculus'],

            // ── Calculus - Derivatives of Common Functions ────────────────────
            ['body' => 'What is the derivative of sin(x) with respect to x?', 'correct_answer' => 'cos(x)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of cos(x) with respect to x?', 'correct_answer' => '-sin(x)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of tan(x) with respect to x?', 'correct_answer' => 'sec^2(x)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of e^x with respect to x?', 'correct_answer' => 'e^x', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of ln(x) with respect to x?', 'correct_answer' => '1/x', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of sqrt(x) with respect to x?', 'correct_answer' => '1/(2sqrt(x))', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of 1/x with respect to x?', 'correct_answer' => '-1/x^2', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of cot(x) with respect to x?', 'correct_answer' => '-csc^2(x)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of sec(x) with respect to x?', 'correct_answer' => 'sec(x)tan(x)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of csc(x) with respect to x?', 'correct_answer' => '-csc(x)cot(x)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of a^x with respect to x, for a general constant base a?', 'correct_answer' => 'a^x ln(a)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of log base 10 of x with respect to x?', 'correct_answer' => '1/(x ln(10))', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of arcsin(x) with respect to x?', 'correct_answer' => '1/sqrt(1-x^2)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of arctan(x) with respect to x?', 'correct_answer' => '1/(1+x^2)', 'category' => 'Calculus'],
            ['body' => 'What is the derivative of e^(2x) with respect to x?', 'correct_answer' => '2e^(2x)', 'category' => 'Calculus'],

            // ── Calculus - Derivatives at a Point ─────────────────────────────
            ['body' => 'If f(x) = x^2, what is f\'(3)?', 'correct_answer' => '6', 'category' => 'Calculus'],
            ['body' => 'If f(x) = x^3, what is f\'(2)?', 'correct_answer' => '12', 'category' => 'Calculus'],
            ['body' => 'If f(x) = x^2, what is f\'(5)?', 'correct_answer' => '10', 'category' => 'Calculus'],
            ['body' => 'If f(x) = 2x^3, what is f\'(1)?', 'correct_answer' => '6', 'category' => 'Calculus'],
            ['body' => 'If f(x) = x^4, what is f\'(1)?', 'correct_answer' => '4', 'category' => 'Calculus'],
            ['body' => 'If f(x) = 3x^2, what is f\'(2)?', 'correct_answer' => '12', 'category' => 'Calculus'],
            ['body' => 'If f(x) = x^2 + 3x, what is f\'(0)?', 'correct_answer' => '3', 'category' => 'Calculus'],
            ['body' => 'If f(x) = 5x, what is f\'(10)?', 'correct_answer' => '5', 'category' => 'Calculus'],
            ['body' => 'If f(x) = x^3 - x, what is f\'(1)?', 'correct_answer' => '2', 'category' => 'Calculus'],
            ['body' => 'If f(x) = 4x^2, what is f\'(3)?', 'correct_answer' => '24', 'category' => 'Calculus'],

            // ── Calculus - Basic Indefinite Integrals ─────────────────────────
            ['body' => 'What is the indefinite integral of x with respect to x?', 'correct_answer' => 'x^2/2 + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of x^2 with respect to x?', 'correct_answer' => 'x^3/3 + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of x^3 with respect to x?', 'correct_answer' => 'x^4/4 + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of x^4 with respect to x?', 'correct_answer' => 'x^5/5 + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of 1 with respect to x?', 'correct_answer' => 'x + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of 2x with respect to x?', 'correct_answer' => 'x^2 + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of 3x^2 with respect to x?', 'correct_answer' => 'x^3 + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of x^5 with respect to x?', 'correct_answer' => 'x^6/6 + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of 1/x with respect to x?', 'correct_answer' => 'ln|x| + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of e^x with respect to x?', 'correct_answer' => 'e^x + c', 'category' => 'Calculus'],

            // ── Calculus - Integrals of Common Functions ──────────────────────
            ['body' => 'What is the indefinite integral of sin(x) with respect to x?', 'correct_answer' => '-cos(x) + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of cos(x) with respect to x?', 'correct_answer' => 'sin(x) + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of sec^2(x) with respect to x?', 'correct_answer' => 'tan(x) + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of 1/(1+x^2) with respect to x?', 'correct_answer' => 'arctan(x) + c', 'category' => 'Calculus'],
            ['body' => 'What is the indefinite integral of e^(2x) with respect to x?', 'correct_answer' => '(1/2)e^(2x) + c', 'category' => 'Calculus'],

            // ── Calculus - Definite Integrals ──────────────────────────────────
            ['body' => 'What is the value of the definite integral of x dx from 0 to 1?', 'correct_answer' => '1/2', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of x dx from 0 to 2?', 'correct_answer' => '2', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of x^2 dx from 0 to 1?', 'correct_answer' => '1/3', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of x^2 dx from 0 to 2?', 'correct_answer' => '8/3', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of 1 dx from 0 to 3?', 'correct_answer' => '3', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of x dx from 1 to 2?', 'correct_answer' => '3/2', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of 2x dx from 0 to 1?', 'correct_answer' => '1', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of sin(x) dx from 0 to pi?', 'correct_answer' => '2', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of x^3 dx from 0 to 1?', 'correct_answer' => '1/4', 'category' => 'Calculus'],
            ['body' => 'What is the value of the definite integral of 1 dx from 0 to 4?', 'correct_answer' => '4', 'category' => 'Calculus'],

            // ── Calculus - Limits ──────────────────────────────────────────────
            ['body' => 'What is the limit of sin(x)/x as x approaches 0?', 'correct_answer' => '1', 'category' => 'Calculus'],
            ['body' => 'What is the limit of 1/x as x approaches infinity?', 'correct_answer' => '0', 'category' => 'Calculus'],
            ['body' => 'What is the limit of (1-cos(x))/x as x approaches 0?', 'correct_answer' => '0', 'category' => 'Calculus'],
            ['body' => 'What is the limit of (1 + 1/x)^x as x approaches infinity?', 'correct_answer' => 'e', 'category' => 'Calculus'],
            ['body' => 'What is the limit of (x^2 - 4)/(x - 2) as x approaches 2?', 'correct_answer' => '4', 'category' => 'Calculus'],
            ['body' => 'What is the limit of x as x approaches 0?', 'correct_answer' => '0', 'category' => 'Calculus'],
            ['body' => 'What is the limit of the constant 5 as x approaches 3?', 'correct_answer' => '5', 'category' => 'Calculus'],
            ['body' => 'What is the limit of 1/x^2 as x approaches infinity?', 'correct_answer' => '0', 'category' => 'Calculus'],
            ['body' => 'What is the limit of (x^2 - 1)/(x - 1) as x approaches 1?', 'correct_answer' => '2', 'category' => 'Calculus'],
            ['body' => 'What is the limit of (e^x - 1)/x as x approaches 0?', 'correct_answer' => '1', 'category' => 'Calculus'],

            // ── Calculus - Theorems & Definitions ─────────────────────────────
            ['body' => 'What theorem states that a continuous function on [a,b] takes on every value between f(a) and f(b)?', 'correct_answer' => 'intermediate value theorem', 'category' => 'Calculus'],
            ['body' => 'What theorem states that if f is continuous on [a,b] and differentiable on (a,b), there exists a point c where f\'(c) equals the average rate of change over [a,b]?', 'correct_answer' => 'mean value theorem', 'category' => 'Calculus'],
            ['body' => 'What theorem links differentiation and integration as inverse processes?', 'correct_answer' => 'fundamental theorem of calculus', 'category' => 'Calculus'],
            ['body' => 'What is the name of the rule used to differentiate a composite function?', 'correct_answer' => 'chain rule', 'category' => 'Calculus'],
            ['body' => 'What is the name of the rule stating that the derivative of uv is u\'v + uv\'?', 'correct_answer' => 'product rule', 'category' => 'Calculus'],
            ['body' => 'What is the name of the rule stating that the derivative of u/v is (u\'v - uv\')/v^2?', 'correct_answer' => 'quotient rule', 'category' => 'Calculus'],
            ['body' => 'What technique evaluates limits of indeterminate forms like 0/0 by differentiating the numerator and denominator?', 'correct_answer' => 'lhopitals rule', 'category' => 'Calculus'],
            ['body' => 'What is the term for a function whose derivative gives back the original function, used in integration?', 'correct_answer' => 'antiderivative', 'category' => 'Calculus'],
            ['body' => 'What is the term for the rate of change of a function at a single instant, defined as a limit?', 'correct_answer' => 'derivative', 'category' => 'Calculus'],
            ['body' => 'What is the process of finding the area under a curve called?', 'correct_answer' => 'integration', 'category' => 'Calculus'],

        ];

        foreach ($questions as $q) {
            Question::firstOrCreate(['body' => $q['body']], $q);
        }

        $this->command->info('Seeded ' . count($questions) . ' hard subject questions.');
    }
}
