<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [

            // // ── Naruto ────────────────────────────────────────────────────────
            // ['body' => 'What is the name of the Nine-Tailed Fox sealed inside Naruto?', 'correct_answer' => 'kurama', 'category' => 'Naruto'],
            // ['body' => 'What village is Naruto Uzumaki from?', 'correct_answer' => 'hidden leaf village', 'category' => 'Naruto'],
            // ['body' => 'Who is Naruto\'s father?', 'correct_answer' => 'minato namikaze', 'category' => 'Naruto'],
            // ['body' => 'What is the name of Naruto\'s signature jutsu?', 'correct_answer' => 'rasengan', 'category' => 'Naruto'],
            // ['body' => 'Who is the jonin sensei of Team 7?', 'correct_answer' => 'kakashi hatake', 'category' => 'Naruto'],
            // ['body' => 'What clan does Sasuke Uchiha belong to?', 'correct_answer' => 'uchiha clan', 'category' => 'Naruto'],
            // ['body' => 'What is the name of Sasuke\'s older brother?', 'correct_answer' => 'itachi uchiha', 'category' => 'Naruto'],

            // // ── Dragon Ball ───────────────────────────────────────────────────
            // ['body' => 'What is Goku\'s Saiyan birth name?', 'correct_answer' => 'kakarot', 'category' => 'Dragon Ball'],
            // ['body' => 'What is the name of Goku\'s signature energy attack?', 'correct_answer' => 'kamehameha', 'category' => 'Dragon Ball'],
            // ['body' => 'What race is Goku?', 'correct_answer' => 'saiyan', 'category' => 'Dragon Ball'],
            // ['body' => 'Who is Goku\'s first martial arts teacher?', 'correct_answer' => 'master roshi', 'category' => 'Dragon Ball'],
            // ['body' => 'What is the name of Goku\'s eldest son?', 'correct_answer' => 'gohan', 'category' => 'Dragon Ball'],
            // ['body' => 'What is Vegeta\'s royal title?', 'correct_answer' => 'prince of all saiyans', 'category' => 'Dragon Ball'],
            // ['body' => 'How many Dragon Balls are needed to summon Shenron?', 'correct_answer' => '7', 'category' => 'Dragon Ball'],

            // // ── Bleach ────────────────────────────────────────────────────────
            // ['body' => 'What is the name of Ichigo Kurosaki\'s zanpakuto?', 'correct_answer' => 'zangetsu', 'category' => 'Bleach'],
            // ['body' => 'What are Soul Reapers called in Japanese in Bleach?', 'correct_answer' => 'shinigami', 'category' => 'Bleach'],
            // ['body' => 'Who is the main antagonist of Bleach?', 'correct_answer' => 'sosuke aizen', 'category' => 'Bleach'],
            // ['body' => 'What is the name of the hollow world in Bleach?', 'correct_answer' => 'hueco mundo', 'category' => 'Bleach'],
            // ['body' => 'What squad is Rukia Kuchiki originally from?', 'correct_answer' => 'squad 13', 'category' => 'Bleach'],
            // ['body' => 'What is Ichigo\'s final Getsuga Tensho transformation called?', 'correct_answer' => 'mugetsu', 'category' => 'Bleach'],

            // // ── One Piece ─────────────────────────────────────────────────────
            // ['body' => 'What is the name of Luffy\'s pirate crew?', 'correct_answer' => 'straw hat pirates', 'category' => 'One Piece'],
            // ['body' => 'What Devil Fruit did Monkey D. Luffy eat?', 'correct_answer' => 'gomu gomu no mi', 'category' => 'One Piece'],
            // ['body' => 'What is the name of the legendary treasure everyone seeks in One Piece?', 'correct_answer' => 'one piece', 'category' => 'One Piece'],
            // ['body' => 'What is the name of the Straw Hats\' second ship?', 'correct_answer' => 'thousand sunny', 'category' => 'One Piece'],
            // ['body' => 'What is the name of Zoro\'s three-sword fighting style?', 'correct_answer' => 'santoryu', 'category' => 'One Piece'],
            // ['body' => 'Who is Luffy\'s grandfather?', 'correct_answer' => 'monkey d. garp', 'category' => 'One Piece'],
            // ['body' => 'What organization does Nico Robin previously work for?', 'correct_answer' => 'baroque works', 'category' => 'One Piece'],

            // // ── Fairy Tail ────────────────────────────────────────────────────
            // ['body' => 'Who is the main protagonist of Fairy Tail?', 'correct_answer' => 'natsu dragneel', 'category' => 'Fairy Tail'],
            // ['body' => 'What type of magic does Natsu Dragneel use?', 'correct_answer' => 'fire dragon slayer magic', 'category' => 'Fairy Tail'],
            // ['body' => 'What is the name of Natsu\'s exceed companion?', 'correct_answer' => 'happy', 'category' => 'Fairy Tail'],
            // ['body' => 'Who is the guild master of Fairy Tail?', 'correct_answer' => 'makarov dreyar', 'category' => 'Fairy Tail'],
            // ['body' => 'What is the name of Erza Scarlet\'s magic that allows her to swap armor?', 'correct_answer' => 'requip', 'category' => 'Fairy Tail'],
            // ['body' => 'What is the name of the ice-make mage in Fairy Tail?', 'correct_answer' => 'gray fullbuster', 'category' => 'Fairy Tail'],

            // // ── Attack on Titan ───────────────────────────────────────────────
            // ['body' => 'Who is the main protagonist of Attack on Titan?', 'correct_answer' => 'eren yeager', 'category' => 'Attack on Titan'],
            // ['body' => 'What is the name of the outermost wall in Attack on Titan?', 'correct_answer' => 'wall maria', 'category' => 'Attack on Titan'],
            // ['body' => 'Who is known as humanity\'s strongest soldier in Attack on Titan?', 'correct_answer' => 'levi ackerman', 'category' => 'Attack on Titan'],
            // ['body' => 'What is the name of the military branch that ventures beyond the walls?', 'correct_answer' => 'survey corps', 'category' => 'Attack on Titan'],
            // ['body' => 'What titan form does Eren first transform into?', 'correct_answer' => 'attack titan', 'category' => 'Attack on Titan'],
            // ['body' => 'Who is Eren\'s childhood friend known for exceptional combat skills?', 'correct_answer' => 'mikasa ackerman', 'category' => 'Attack on Titan'],
            // ['body' => 'What is the name of the armored titan in Attack on Titan?', 'correct_answer' => 'reiner braun', 'category' => 'Attack on Titan'],

            // // ── Another ───────────────────────────────────────────────────────
            // ['body' => 'What is the name of the cursed class in the anime Another?', 'correct_answer' => 'class 3-3', 'category' => 'Another'],
            // ['body' => 'Who is the mysterious girl with an eye patch in Another?', 'correct_answer' => 'mei misaki', 'category' => 'Another'],
            // ['body' => 'In which school does the story of Another take place?', 'correct_answer' => 'yomiyama north middle school', 'category' => 'Another'],

            // // ── My Hero Academia ──────────────────────────────────────────────
            // ['body' => 'What is the term for superpowers in My Hero Academia?', 'correct_answer' => 'quirk', 'category' => 'My Hero Academia'],
            // ['body' => 'Who is the main protagonist of My Hero Academia?', 'correct_answer' => 'izuku midoriya', 'category' => 'My Hero Academia'],
            // ['body' => 'What is the name of the hero high school in My Hero Academia?', 'correct_answer' => 'u.a. high school', 'category' => 'My Hero Academia'],
            // ['body' => 'What is Izuku Midoriya\'s hero name?', 'correct_answer' => 'deku', 'category' => 'My Hero Academia'],
            // ['body' => 'What is the name of All Might\'s quirk passed down to Deku?', 'correct_answer' => 'one for all', 'category' => 'My Hero Academia'],
            // ['body' => 'What is the name of Bakugo\'s quirk in My Hero Academia?', 'correct_answer' => 'explosion', 'category' => 'My Hero Academia'],
            // ['body' => 'Who is the main villain organization in My Hero Academia?', 'correct_answer' => 'league of villains', 'category' => 'My Hero Academia'],

            // // ── Unusual General Trivia ─────────────────────────────────────────
            // ['body' => 'What is the name of the fear of long words?', 'correct_answer' => 'hippopotomonstrosesquippedaliophobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'What color is a polar bear\'s skin under its white fur?', 'correct_answer' => 'black', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many hearts does an octopus have?', 'correct_answer' => '3', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only mammal that cannot jump?', 'correct_answer' => 'elephant', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the loudest animal on Earth?', 'correct_answer' => 'sperm whale', 'category' => 'Unusual Trivia'],
            // ['body' => 'What fruit has its seeds on the outside?', 'correct_answer' => 'strawberry', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many noses does a slug have?', 'correct_answer' => '4', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only letter not appearing on the periodic table?', 'correct_answer' => 'j', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the world\'s most venomous fish?', 'correct_answer' => 'stonefish', 'category' => 'Unusual Trivia'],
            // ['body' => 'A group of flamingos is called a what?', 'correct_answer' => 'flamboyance', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the shortest war in history and how long did it last?', 'correct_answer' => 'anglo-zanzibar war, 38 minutes', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which planet rains diamonds?', 'correct_answer' => 'neptune', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the name of the process by which a lobster eats another lobster?', 'correct_answer' => 'cannibalism', 'category' => 'Unusual Trivia'],
            // ['body' => 'What color do you bleed in space (due to vacuum effects on blood)?', 'correct_answer' => 'red', 'category' => 'Unusual Trivia'],
            // ['body' => 'What animal has the most teeth?', 'correct_answer' => 'snail', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many bones does a shark have?', 'correct_answer' => '0', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the collective noun for a group of crows?', 'correct_answer' => 'murder', 'category' => 'Unusual Trivia'],
            // ['body' => 'What percentage of the ocean is unexplored?', 'correct_answer' => '80', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the most shoplifted food item in the world?', 'correct_answer' => 'cheese', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which country invented the guillotine?', 'correct_answer' => 'france', 'category' => 'Unusual Trivia'],
            // ['body' => 'What was the first toy advertised on television?', 'correct_answer' => 'mr. potato head', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only food that never expires?', 'correct_answer' => 'honey', 'category' => 'Unusual Trivia'],
            // ['body' => 'How long can a cockroach survive without its head?', 'correct_answer' => 'one week', 'category' => 'Unusual Trivia'],
            // ['body' => 'What animal can sleep for three years?', 'correct_answer' => 'snail', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the longest recorded flight of a chicken?', 'correct_answer' => '13 seconds', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which body part continues to grow your entire life?', 'correct_answer' => 'ears and nose', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the fear of belly buttons called?', 'correct_answer' => 'omphalophobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only planet in our solar system that rotates clockwise?', 'correct_answer' => 'venus', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the world\'s smallest country by area?', 'correct_answer' => 'vatican city', 'category' => 'Unusual Trivia'],
            // ['body' => 'Cleopatra lived closer in time to the moon landing or the construction of the Great Pyramid?', 'correct_answer' => 'moon landing', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the strongest muscle in the human body relative to its size?', 'correct_answer' => 'masseter (jaw muscle)', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many dimples does a regulation golf ball have?', 'correct_answer' => '336', 'category' => 'Unusual Trivia'],
            // ['body' => 'What color is the blood of an octopus?', 'correct_answer' => 'blue', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which country has the most natural lakes in the world?', 'correct_answer' => 'canada', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the hardest natural substance on Earth?', 'correct_answer' => 'diamond', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the name of the phobia of the number 13?', 'correct_answer' => 'triskaidekaphobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which animal is the only one known to die from loneliness?', 'correct_answer' => 'rabbit', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the most common name in the world?', 'correct_answer' => 'muhammad', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many bones are babies born with compared to adults?', 'correct_answer' => '94 more', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only continent with no active volcanoes?', 'correct_answer' => 'australia', 'category' => 'Unusual Trivia'],
            // ['body' => 'How far does the human eye see clearly in miles?', 'correct_answer' => '3 miles', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is a group of porcupines called?', 'correct_answer' => 'a prickle', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the world\'s most consumed spice?', 'correct_answer' => 'pepper', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only insect that can turn its head 180 degrees?', 'correct_answer' => 'praying mantis', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which animal has the highest blood pressure?', 'correct_answer' => 'giraffe', 'category' => 'Unusual Trivia'],
            // ['body' => 'How much of the world\'s oxygen is produced by the Amazon rainforest?', 'correct_answer' => '20 percent', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the fear of running out of things to read called?', 'correct_answer' => 'abibliophobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only bird that can fly backwards?', 'correct_answer' => 'hummingbird', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many eyes does a bee have?', 'correct_answer' => '5', 'category' => 'Unusual Trivia'],
            // ['body' => 'What color is a mirror?', 'correct_answer' => 'green', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the longest word in the English language that can be typed using only the top row of a keyboard?', 'correct_answer' => 'typewriter', 'category' => 'Unusual Trivia'],
            // ['body' => 'How long does it take for a glass bottle to decompose?', 'correct_answer' => '1 million years', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which planet has the most moons in our solar system?', 'correct_answer' => 'saturn', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the fear of being watched by a duck called?', 'correct_answer' => 'anatidaephobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many languages are spoken in Papua New Guinea?', 'correct_answer' => '850', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the rarest blood type in humans?', 'correct_answer' => 'ab negative', 'category' => 'Unusual Trivia'],
            // ['body' => 'What mammal has the most powerful bite in the world?', 'correct_answer' => 'hippopotamus', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only rock eaten by humans?', 'correct_answer' => 'salt', 'category' => 'Unusual Trivia'],
            // ['body' => 'What percentage of humans have an outie belly button?', 'correct_answer' => '10 percent', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the average number of times a person blinks per year?', 'correct_answer' => '4.2 million', 'category' => 'Unusual Trivia'],
            // ['body' => 'What country consumes the most chocolate per capita?', 'correct_answer' => 'switzerland', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the name for a fear of peanut butter sticking to the roof of your mouth?', 'correct_answer' => 'arachibutyrophobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'A shrimp\'s heart is located where on its body?', 'correct_answer' => 'in its head', 'category' => 'Unusual Trivia'],
            // ['body' => 'What animal cannot vomit?', 'correct_answer' => 'horse', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the world\'s oldest known living tree species?', 'correct_answer' => 'ginkgo biloba', 'category' => 'Unusual Trivia'],
            // ['body' => 'How long can a tardigrade survive without water?', 'correct_answer' => '30 years', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the collective noun for a group of owls?', 'correct_answer' => 'parliament', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which country has the most pyramids in the world?', 'correct_answer' => 'sudan', 'category' => 'Unusual Trivia'],
            // ['body' => 'What fruit is technically a berry but a strawberry is not?', 'correct_answer' => 'banana', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the fear of the number 666 called?', 'correct_answer' => 'hexakosioihexekontahexaphobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many noses does a cow have?', 'correct_answer' => '1', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the world\'s largest desert that is not sand?', 'correct_answer' => 'antarctica', 'category' => 'Unusual Trivia'],
            // ['body' => 'What color is the tongue of a giraffe?', 'correct_answer' => 'black', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many times does a hummingbird\'s heart beat per minute?', 'correct_answer' => '1200', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which famous scientist was offered the presidency of Israel but declined?', 'correct_answer' => 'albert einstein', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the name of the phenomenon where you can hear your heartbeat in your ear?', 'correct_answer' => 'pulsatile tinnitus', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only planet not named after a god?', 'correct_answer' => 'earth', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many stomachs does a cow have?', 'correct_answer' => '4', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the term for the smell of rain on dry earth?', 'correct_answer' => 'petrichor', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the fear of being buried alive called?', 'correct_answer' => 'taphophobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which country invented ice cream?', 'correct_answer' => 'china', 'category' => 'Unusual Trivia'],
            // ['body' => 'A group of jellyfish is called a what?', 'correct_answer' => 'smack', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the fastest growing plant on Earth?', 'correct_answer' => 'bamboo', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many bones are in the human hand?', 'correct_answer' => '27', 'category' => 'Unusual Trivia'],
            // ['body' => 'What percentage of your DNA is shared with a banana?', 'correct_answer' => '50 percent', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the word for the dot above the letters "i" and "j"?', 'correct_answer' => 'tittle', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the most common eye color in the world?', 'correct_answer' => 'brown', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which sea creature has no brain or heart?', 'correct_answer' => 'jellyfish', 'category' => 'Unusual Trivia'],
            // ['body' => 'What country has the most time zones?', 'correct_answer' => 'france', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the most isolated tree in the world?', 'correct_answer' => 'tree of ténéré', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the fear of mirrors called?', 'correct_answer' => 'eisoptrophobia', 'category' => 'Unusual Trivia'],
            // ['body' => 'How many hearts does an earthworm have?', 'correct_answer' => '5', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the only animal born with horns?', 'correct_answer' => 'giraffe', 'category' => 'Unusual Trivia'],
            // ['body' => 'How far does lightning extend above the clouds into space?', 'correct_answer' => '60 miles', 'category' => 'Unusual Trivia'],
            // ['body' => 'What ancient civilization invented concrete?', 'correct_answer' => 'romans', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the term for a word that reads the same forwards and backwards?', 'correct_answer' => 'palindrome', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which animal technically never sleeps?', 'correct_answer' => 'bullfrog', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the most venomous creature on Earth?', 'correct_answer' => 'box jellyfish', 'category' => 'Unusual Trivia'],
            // ['body' => 'What letter is the most used in the English alphabet?', 'correct_answer' => 'e', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the smallest planet in our solar system?', 'correct_answer' => 'mercury', 'category' => 'Unusual Trivia'],
            // ['body' => 'Which animal can recognize itself in a mirror?', 'correct_answer' => 'elephant', 'category' => 'Unusual Trivia'],
            // ['body' => 'What is the term for the blank space between words on a page?', 'correct_answer' => 'leading', 'category' => 'Unusual Trivia'],

            // // ── Songs (Hard) ──────────────────────────────────────────────────
            // ['body' => 'Which everyday office machine provides the looping percussive sound throughout Pink Floyd\'s "Money"?', 'correct_answer' => 'a cash register', 'category' => 'Songs'],
            // ['body' => 'What was Kurt Cobain\'s reported working title for "Smells Like Teen Spirit" before the final name was chosen?', 'correct_answer' => 'the incest song', 'category' => 'Songs'],
            // ['body' => 'What deodorant brand name did bandmate Kathleen Hanna spray-paint on Kurt Cobain\'s wall, inspiring the title "Smells Like Teen Spirit"?', 'correct_answer' => 'teen spirit', 'category' => 'Songs'],
            // ['body' => 'Freddie Mercury originally titled "Bohemian Rhapsody" something else while recording it in secret from the record label. What was it?', 'correct_answer' => 'champagne', 'category' => 'Songs'],
            // ['body' => 'What is the very first word sung in "Bohemian Rhapsody"?', 'correct_answer' => 'is', 'category' => 'Songs'],
            // ['body' => 'Which commedia dell\'arte stock character is shouted repeatedly during the operatic section of "Bohemian Rhapsody"?', 'correct_answer' => 'scaramouche', 'category' => 'Songs'],
            // ['body' => 'What Arabic phrase, meaning roughly "I will not allow it," is sung during the operatic section of "Bohemian Rhapsody"?', 'correct_answer' => 'bismillah', 'category' => 'Songs'],
            // ['body' => 'Which London radio DJ is credited with playing an advance copy of "Bohemian Rhapsody" fourteen times over one weekend?', 'correct_answer' => 'kenny everett', 'category' => 'Songs'],
            // ['body' => 'What was the B-side track on the original 1975 "Bohemian Rhapsody" single?', 'correct_answer' => 'im in love with my car', 'category' => 'Songs'],
            // ['body' => 'What horror film legend delivers the closing spoken monologue on Michael Jackson\'s "Thriller"?', 'correct_answer' => 'vincent price', 'category' => 'Songs'],
            // ['body' => 'Which director of An American Werewolf in London directed the "Thriller" short film?', 'correct_answer' => 'john landis', 'category' => 'Songs'],
            // ['body' => 'What classmate\'s name appeared on the crayon drawing by Julian Lennon that inspired "Lucy in the Sky with Diamonds"?', 'correct_answer' => 'lucy odonnell', 'category' => 'Songs'],
            // ['body' => 'What sea creature gives its name to the Ringo Starr-penned Beatles song on Abbey Road?', 'correct_answer' => 'an octopus', 'category' => 'Songs'],
            // ['body' => 'Which guitarist famously performed a solo rendition of "The Star-Spangled Banner" at Woodstock in 1969?', 'correct_answer' => 'jimi hendrix', 'category' => 'Songs'],
            // ['body' => 'What was Radiohead\'s "Creep" retroactively given co-writing credits for, due to its melodic similarity to another song?', 'correct_answer' => 'the air that i breathe', 'category' => 'Songs'],
            // ['body' => 'Which two songwriters received a retroactive royalty settlement and writing credit on Radiohead\'s "Creep"?', 'correct_answer' => 'albert hammond and mike hazlewood', 'category' => 'Songs'],
            // ['body' => 'Which 1963 novelty single triggered a two-year FBI investigation into supposedly obscene, indecipherable lyrics?', 'correct_answer' => 'louie louie', 'category' => 'Songs'],
            // ['body' => 'Which garage rock band recorded the 1963 version of "Louie Louie" that the FBI investigated?', 'correct_answer' => 'the kingsmen', 'category' => 'Songs'],
            // ['body' => 'Which Prince side project originally released "Nothing Compares 2 U" in 1985, years before Sinead O\'Connor\'s cover?', 'correct_answer' => 'the family', 'category' => 'Songs'],
            // ['body' => 'Which country legend originally wrote and recorded "I Will Always Love You" before Whitney Houston\'s version?', 'correct_answer' => 'dolly parton', 'category' => 'Songs'],
            // ['body' => 'Which musical mentor and duet partner did Dolly Parton write "I Will Always Love You" about, as a professional farewell?', 'correct_answer' => 'porter wagoner', 'category' => 'Songs'],
            // ['body' => 'What object does Robert Plant compare a lover to when he sings "squeeze my lemon" in Led Zeppelin\'s "The Lemon Song"?', 'correct_answer' => 'a lemon', 'category' => 'Songs'],
            // ['body' => 'Which drummer joked that Led Zeppelin\'s new band name would "go down like a lead balloon," inspiring the group\'s name?', 'correct_answer' => 'keith moon', 'category' => 'Songs'],
            // ['body' => 'What was Led Zeppelin\'s touring name for a brief period immediately before adopting "Led Zeppelin"?', 'correct_answer' => 'the new yardbirds', 'category' => 'Songs'],
            // ['body' => 'Which music video is officially recognized as the first ever aired on MTV in 1981?', 'correct_answer' => 'video killed the radio star', 'category' => 'Songs'],
            // ['body' => 'Which new wave duo recorded "Video Killed the Radio Star", MTV\'s launch video?', 'correct_answer' => 'the buggles', 'category' => 'Songs'],
            // ['body' => 'What everyday classroom item does the fictional child in "Another Brick in the Wall Part 2" rebel against, giving the song its chant?', 'correct_answer' => 'we dont need no education', 'category' => 'Songs'],
            // ['body' => 'Which school choir performed the memorable children\'s chant on Pink Floyd\'s "Another Brick in the Wall Part 2"?', 'correct_answer' => 'islington green school', 'category' => 'Songs'],
            // ['body' => 'What was the reported one-time session fee paid to saxophonist Raphael Ravenscroft for his iconic solo on Gerry Rafferty\'s "Baker Street"?', 'correct_answer' => 'about 27 pounds', 'category' => 'Songs'],
            // ['body' => 'Which fictional detective\'s address is on the same London street named in Gerry Rafferty\'s "Baker Street"?', 'correct_answer' => 'sherlock holmes', 'category' => 'Songs'],
            // ['body' => 'Which Motown singer\'s "I Heard It Through the Grapevine" became Motown\'s best-selling single up to that point, after Berry Gordy initially held it back?', 'correct_answer' => 'marvin gaye', 'category' => 'Songs'],
            // ['body' => 'Which Four Tops member brought Marvin Gaye the real-life account of police brutality that inspired "What\'s Going On"?', 'correct_answer' => 'obie benson', 'category' => 'Songs'],
            // ['body' => 'Which session saxophonist\'s improvised warmup take became the famous outro solo kept on Marvin Gaye\'s "What\'s Going On"?', 'correct_answer' => 'eli fontaine', 'category' => 'Songs'],
            // ['body' => 'Which soul singer died in a plane crash just days before his song "(Sittin\' On) The Dock of the Bay" was released?', 'correct_answer' => 'otis redding', 'category' => 'Songs'],
            // ['body' => 'What did Otis Redding do instead of singing a forgotten lyric at the end of "(Sittin\' On) The Dock of the Bay", creating its famous outro?', 'correct_answer' => 'he whistled', 'category' => 'Songs'],
            // ['body' => 'Which real Tennessee lounge did Billy Joel perform at under the fake name "Bill Martin," the experience that inspired "Piano Man"?', 'correct_answer' => 'the executive room', 'category' => 'Songs'],
            // ['body' => 'What handwritten sign hung on the studio door during the all-night recording of "We Are the World" in 1985?', 'correct_answer' => 'check your ego at the door', 'category' => 'Songs'],
            // ['body' => 'Which two artists co-wrote "We Are the World" for the USA for Africa charity single?', 'correct_answer' => 'michael jackson and lionel richie', 'category' => 'Songs'],
            // ['body' => 'Which British charity single, organized by Bob Geldof and Midge Ure in 1984, directly inspired "We Are the World"?', 'correct_answer' => 'do they know its christmas', 'category' => 'Songs'],
            // ['body' => 'Which stadium hosted Queen\'s legendary 20-minute Live Aid set in 1985?', 'correct_answer' => 'wembley stadium', 'category' => 'Songs'],
            // ['body' => 'Whose divorce inspired Paul McCartney to write "Hey Jude", originally addressed to "Jules" before the name was shortened?', 'correct_answer' => 'julian lennon', 'category' => 'Songs'],
            // ['body' => 'What real 1975 shipwreck on Lake Superior is chronicled in detail by Gordon Lightfoot\'s "The Wreck of the Edmund Fitzgerald"?', 'correct_answer' => 'the sinking of the ss edmund fitzgerald', 'category' => 'Songs'],
            // ['body' => 'How many crew members were lost when the Edmund Fitzgerald sank, as the song\'s lyrics commemorate?', 'correct_answer' => '29', 'category' => 'Songs'],
            // ['body' => 'Which prison did Johnny Cash famously record a live album at in 1968, despite never having served time there himself?', 'correct_answer' => 'folsom state prison', 'category' => 'Songs'],
            // ['body' => 'What was Bob Dylan\'s birth name before he adopted his stage surname?', 'correct_answer' => 'robert allen zimmerman', 'category' => 'Songs'],
            // ['body' => 'Which Welsh poet is widely believed to have inspired Bob Dylan\'s chosen stage surname?', 'correct_answer' => 'dylan thomas', 'category' => 'Songs'],
            // ['body' => 'What single word did an audience member shout at Bob Dylan during his controversial 1966 "electric" tour, accusing him of betrayal?', 'correct_answer' => 'judas', 'category' => 'Songs'],
            // ['body' => 'Which folk trio\'s cover of "Blowin\' in the Wind" became a bigger hit in 1963 than Bob Dylan\'s own original version?', 'correct_answer' => 'peter paul and mary', 'category' => 'Songs'],
            // ['body' => 'What zebra crossing, made famous by an album cover, is located outside Abbey Road Studios in London?', 'correct_answer' => 'the abbey road zebra crossing', 'category' => 'Songs'],
            // ['body' => 'What conspiracy theory grew out of Paul McCartney appearing barefoot on the Abbey Road album cover?', 'correct_answer' => 'paul is dead', 'category' => 'Songs'],
            // ['body' => 'Which Beatle plays the only drum solo he ever recorded on a Beatles song, during "The End"?', 'correct_answer' => 'ringo starr', 'category' => 'Songs'],
            // ['body' => 'What is the final sung line of The Beatles\' song "The End", often considered the band\'s parting message?', 'correct_answer' => 'and in the end the love you take is equal to the love you make', 'category' => 'Songs'],
            // ['body' => 'What hidden track plays after "Her Majesty" was originally cut from, then spliced back onto the very end of Abbey Road almost by accident?', 'correct_answer' => 'her majesty', 'category' => 'Songs'],
            // ['body' => 'Which cult leader claimed The Beatles\' self-titled "White Album" contained coded messages predicting a race war he called "Helter Skelter"?', 'correct_answer' => 'charles manson', 'category' => 'Songs'],
            // ['body' => 'What fairground ride inspired the title of The Beatles\' heavy, chaotic song "Helter Skelter"?', 'correct_answer' => 'a helter skelter slide', 'category' => 'Songs'],
            // ['body' => 'What does Ringo Starr famously shout at the very end of "Helter Skelter", left in the final mix?', 'correct_answer' => 'ive got blisters on my fingers', 'category' => 'Songs'],
            // ['body' => 'Which Who guitarist\'s description of a raucous, dirty-sounding song inspired Paul McCartney to write "Helter Skelter"?', 'correct_answer' => 'pete townshend', 'category' => 'Songs'],
            // ['body' => 'Which Nigerian conga player\'s catchphrase "life goes on" inspired the nonsensical title of The Beatles\' "Ob-La-Di, Ob-La-Da"?', 'correct_answer' => 'jimmy scott', 'category' => 'Songs'],
            // ['body' => 'What are the names of the fictional market-stall couple described in the lyrics of "Ob-La-Di, Ob-La-Da"?', 'correct_answer' => 'desmond and molly jones', 'category' => 'Songs'],
            // ['body' => 'What was the very first single The Beatles released in the UK, in October 1962?', 'correct_answer' => 'love me do', 'category' => 'Songs'],
            // ['body' => 'Which session drummer, not Ringo Starr, played on the most commonly released single version of "Love Me Do"?', 'correct_answer' => 'andy white', 'category' => 'Songs'],
            // ['body' => 'Which American television program gave The Beatles their famous 1964 US debut, watched by a record-breaking audience?', 'correct_answer' => 'the ed sullivan show', 'category' => 'Songs'],
            // ['body' => 'What controversial 1966 remark did John Lennon make comparing The Beatles\' popularity to Jesus, sparking record burnings in the American South?', 'correct_answer' => 'we are more popular than jesus now', 'category' => 'Songs'],
            // ['body' => 'Whose breakfast invitation did The Beatles unintentionally snub in Manila in 1966, leading to a hostile mob at the airport?', 'correct_answer' => 'imelda marcos', 'category' => 'Songs'],
            // ['body' => 'At which San Francisco venue did The Beatles play their final official paid concert in 1966?', 'correct_answer' => 'candlestick park', 'category' => 'Songs'],
            // ['body' => 'On what London street\'s rooftop did The Beatles play their final live performance together in January 1969?', 'correct_answer' => 'savile row', 'category' => 'Songs'],
            // ['body' => 'What quip did John Lennon make immediately after The Beatles finished their famous rooftop concert in 1969?', 'correct_answer' => 'i hope we passed the audition', 'category' => 'Songs'],
            // ['body' => 'Which 1968 instrumental by the band Spirit led to a decades-later copyright lawsuit against Led Zeppelin\'s "Stairway to Heaven"?', 'correct_answer' => 'taurus', 'category' => 'Songs'],
            // ['body' => 'Which Spirit guitarist wrote "Taurus", the song at the center of the "Stairway to Heaven" copyright lawsuit?', 'correct_answer' => 'randy california', 'category' => 'Songs'],
            // ['body' => 'What urban legend claims a satanic message about "my sweet Satan" can be heard when "Stairway to Heaven" is played backwards?', 'correct_answer' => 'backmasking', 'category' => 'Songs'],
            // ['body' => 'In the 1992 comedy Wayne\'s World, what wording appears on the guitar shop sign banning a certain overplayed song?', 'correct_answer' => 'no stairway to heaven', 'category' => 'Songs'],
            // ['body' => 'Which songwriting duo wrote the bluegrass standard "Rocky Top" in under 15 minutes?', 'correct_answer' => 'boudleaux and felice bryant', 'category' => 'Songs'],
            // ['body' => 'Which university\'s sports teams adopted "Rocky Top" as an unofficial fight song, though the song predates the association?', 'correct_answer' => 'the university of tennessee', 'category' => 'Songs'],
            // ['body' => 'How many official state songs does Tennessee have, including "Rocky Top"?', 'correct_answer' => 'nine', 'category' => 'Songs'],
            // ['body' => 'Which folk singer\'s "This Land Is Your Land" was written partly as a critical response to Irving Berlin\'s "God Bless America"?', 'correct_answer' => 'woody guthrie', 'category' => 'Songs'],
            // ['body' => 'What was Woody Guthrie\'s original title for the song that became "This Land Is Your Land"?', 'correct_answer' => 'god blessed america for me', 'category' => 'Songs'],
            // ['body' => 'Which magazine\'s list famously ranked Bob Dylan\'s "Like a Rolling Stone" as the greatest song of all time?', 'correct_answer' => 'rolling stone', 'category' => 'Songs'],
            // ['body' => 'Which musician improvised the famous organ part on "Like a Rolling Stone" despite being asked to play guitar that session?', 'correct_answer' => 'al kooper', 'category' => 'Songs'],
            // ['body' => 'What insulting refrain does Bob Dylan repeat throughout the chorus of "Like a Rolling Stone"?', 'correct_answer' => 'how does it feel', 'category' => 'Songs'],
            // ['body' => 'Which soul singer\'s "Respect", originally written and recorded by Otis Redding, became a feminist anthem in her cover version?', 'correct_answer' => 'aretha franklin', 'category' => 'Songs'],
            // ['body' => 'What spelled-out word does Aretha Franklin famously add to the bridge of her cover of "Respect", absent from Otis Redding\'s original?', 'correct_answer' => 'r e s p e c t', 'category' => 'Songs'],
            // ['body' => 'What phrase does Aretha Franklin add in her "Respect" cover, asking for her due "when you get home"?', 'correct_answer' => 'sock it to me', 'category' => 'Songs'],
            // ['body' => 'Which US president invited Aretha Franklin to sing "Respect" and other hits at a 2015 Kennedy Center Honors tribute to Carole King?', 'correct_answer' => 'barack obama', 'category' => 'Songs'],
            // ['body' => 'What real 1965 Selma-to-Montgomery civil rights event is commemorated by Bob Dylan collaborator turned activist song "We Shall Overcome"?', 'correct_answer' => 'the selma to montgomery march', 'category' => 'Songs'],
            // ['body' => 'Which gospel and folk standard, adapted from a hymn, became the unofficial anthem of the American civil rights movement?', 'correct_answer' => 'we shall overcome', 'category' => 'Songs'],
            // ['body' => 'Which jazz vocalist was famously nearly barred from recording "Strange Fruit", a song about lynching, due to its subject matter?', 'correct_answer' => 'billie holiday', 'category' => 'Songs'],
            // ['body' => 'What is the metaphorical "strange fruit" referenced in the title of Billie Holiday\'s harrowing 1939 protest song?', 'correct_answer' => 'lynched bodies hanging from trees', 'category' => 'Songs'],
            // ['body' => 'Which schoolteacher, writing under a pseudonym, originally wrote the poem that became "Strange Fruit"?', 'correct_answer' => 'abel meeropol', 'category' => 'Songs'],
            // ['body' => 'What label released "Strange Fruit" after Billie Holiday\'s regular label, Columbia, refused due to its controversial content?', 'correct_answer' => 'commodore records', 'category' => 'Songs'],
            // ['body' => 'Which Motown girl group\'s "Where Did Our Love Go" gave the label its first Billboard Hot 100 number-one hit?', 'correct_answer' => 'the supremes', 'category' => 'Songs'],
            // ['body' => 'Which Motown production and songwriting trio wrote most of The Supremes\' biggest 1960s hits?', 'correct_answer' => 'holland dozier holland', 'category' => 'Songs'],
            // ['body' => 'Which Fleetwood Mac album, largely written amid the band\'s internal breakups, produced "Go Your Own Way" and "Dreams"?', 'correct_answer' => 'rumours', 'category' => 'Songs'],
            // ['body' => 'Which Fleetwood Mac member wrote "Go Your Own Way" about her own recent breakup with bandmate Stevie Nicks?', 'correct_answer' => 'lindsey buckingham', 'category' => 'Songs'],
            // ['body' => 'Which Fleetwood Mac song did Stevie Nicks write as a response to Lindsey Buckingham\'s accusatory "Go Your Own Way"?', 'correct_answer' => 'dreams', 'category' => 'Songs'],
            // ['body' => 'What repeated childhood prayer is quoted, then subverted, in the bridge of Metallica\'s "Enter Sandman"?', 'correct_answer' => 'now i lay me down to sleep', 'category' => 'Songs'],
            // ['body' => 'What is the informal nickname of Metallica\'s plain black-covered 1991 self-titled album, which features "Enter Sandman"?', 'correct_answer' => 'the black album', 'category' => 'Songs'],
            // ['body' => 'Which grunge band\'s "Black Hole Sun" features a famously surreal, melting-suburbia music video directed by Howard Greenhalgh?', 'correct_answer' => 'soundgarden', 'category' => 'Songs'],

            // ── IT - Networking ───────────────────────────────────────────────
            ['body' => 'What does the acronym DNS stand for in networking?', 'correct_answer' => 'domain name system', 'category' => 'IT - Networking'],
            ['body' => 'What protocol automatically assigns IP addresses to devices joining a network?', 'correct_answer' => 'dynamic host configuration protocol', 'category' => 'IT - Networking'],
            ['body' => 'What term describes an attack that overwhelms a target using traffic from many compromised devices at once?', 'correct_answer' => 'distributed denial of service', 'category' => 'IT - Networking'],
            ['body' => 'Which OSI model layer is responsible for reliable end-to-end data delivery between hosts?', 'correct_answer' => 'transport layer', 'category' => 'IT - Networking'],
            ['body' => 'What is the secure, encrypted version of HTTP called?', 'correct_answer' => 'hypertext transfer protocol secure', 'category' => 'IT - Networking'],
            ['body' => 'What networking technique lets multiple devices on a private network share one public IP address?', 'correct_answer' => 'network address translation', 'category' => 'IT - Networking'],
            ['body' => 'What link-state routing protocol calculates the shortest path first within a single autonomous system?', 'correct_answer' => 'open shortest path first', 'category' => 'IT - Networking'],
            ['body' => 'What network topology connects every device to a central hub or switch?', 'correct_answer' => 'star topology', 'category' => 'IT - Networking'],
            ['body' => 'What technology allows switches to logically separate a physical network into isolated broadcast domains?', 'correct_answer' => 'virtual local area network', 'category' => 'IT - Networking'],
            ['body' => 'What foundational two-protocol suite, developed for ARPANET, underlies modern internet communication?', 'correct_answer' => 'transmission control protocol and internet protocol', 'category' => 'IT - Networking'],

            // ── IT - Cybersecurity ────────────────────────────────────────────
            ['body' => 'What type of malware disguises itself as legitimate software to trick users into installing it?', 'correct_answer' => 'a trojan horse', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What social engineering attack tricks victims into revealing credentials via fake emails or websites?', 'correct_answer' => 'phishing attack', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What term describes exploiting a software vulnerability before the vendor has released a patch?', 'correct_answer' => 'zero day exploit', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What cryptographic technique converts data into a fixed-length string that cannot be reversed?', 'correct_answer' => 'one way hash function', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What security model requires verifying every user and device, granting no automatic trust regardless of network location?', 'correct_answer' => 'zero trust architecture', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What attack floods a login form with password guesses generated by trying every possible combination?', 'correct_answer' => 'brute force attack', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What malicious technique injects database commands into an input field to manipulate a database?', 'correct_answer' => 'sql injection', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What is the name for malware that encrypts a victim\'s files and demands payment for the decryption key?', 'correct_answer' => 'ransomware attack', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What security practice requires two or more independent credentials before granting account access?', 'correct_answer' => 'multi factor authentication', 'category' => 'IT - Cybersecurity'],
            ['body' => 'What term describes a network of hijacked computers remotely controlled to perform coordinated attacks?', 'correct_answer' => 'a botnet', 'category' => 'IT - Cybersecurity'],

            // ── IT - Programming ──────────────────────────────────────────────
            ['body' => 'What programming paradigm models software as objects that combine state and behavior?', 'correct_answer' => 'object oriented programming', 'category' => 'IT - Programming'],
            ['body' => 'What term describes a function with no side effects that always returns the same output for a given input?', 'correct_answer' => 'pure function', 'category' => 'IT - Programming'],
            ['body' => 'What SOLID principle states a class should have only one reason to change?', 'correct_answer' => 'single responsibility principle', 'category' => 'IT - Programming'],
            ['body' => 'What creational design pattern restricts a class to exactly one shared instance?', 'correct_answer' => 'singleton pattern', 'category' => 'IT - Programming'],
            ['body' => 'What term describes a function that solves a problem by calling itself on smaller sub-problems?', 'correct_answer' => 'recursive function', 'category' => 'IT - Programming'],
            ['body' => 'What term describes code that catches and responds to runtime errors instead of crashing?', 'correct_answer' => 'exception handling', 'category' => 'IT - Programming'],
            ['body' => 'What version control command creates an independent line of development that can later be merged back?', 'correct_answer' => 'git branch', 'category' => 'IT - Programming'],
            ['body' => 'What testing methodology writes automated tests before writing the actual implementation code?', 'correct_answer' => 'test driven development', 'category' => 'IT - Programming'],
            ['body' => 'What term describes gradually restructuring existing code without changing its external behavior?', 'correct_answer' => 'code refactoring', 'category' => 'IT - Programming'],
            ['body' => 'What software architecture style structures an application as small, independently deployable services?', 'correct_answer' => 'microservices architecture', 'category' => 'IT - Programming'],

            // ── IT - Databases ────────────────────────────────────────────────
            ['body' => 'What database language is used to query and manipulate relational data?', 'correct_answer' => 'structured query language', 'category' => 'IT - Databases'],
            ['body' => 'What term describes organizing database tables to reduce redundancy and improve data integrity?', 'correct_answer' => 'database normalization', 'category' => 'IT - Databases'],
            ['body' => 'In database transactions, what does the acronym ACID stand for?', 'correct_answer' => 'atomicity, consistency, isolation, and durability', 'category' => 'IT - Databases'],
            ['body' => 'What type of database stores data as flexible documents rather than fixed rows and columns?', 'correct_answer' => 'a document database', 'category' => 'IT - Databases'],
            ['body' => 'What database structure speeds up lookups by maintaining a sorted reference to table rows?', 'correct_answer' => 'a database index', 'category' => 'IT - Databases'],
            ['body' => 'What term describes copying and synchronizing data across multiple database servers for redundancy?', 'correct_answer' => 'database replication', 'category' => 'IT - Databases'],
            ['body' => 'What SQL join returns only rows that have matching values in both joined tables?', 'correct_answer' => 'inner join', 'category' => 'IT - Databases'],
            ['body' => 'What term describes dividing a database or table across multiple servers to spread load?', 'correct_answer' => 'database sharding', 'category' => 'IT - Databases'],
            ['body' => 'What database anomaly occurs when the same value is duplicated across multiple rows, wasting storage and risking inconsistency?', 'correct_answer' => 'data redundancy', 'category' => 'IT - Databases'],
            ['body' => 'What relational database concept is a column, or set of columns, that uniquely identifies each row in a table?', 'correct_answer' => 'a primary key', 'category' => 'IT - Databases'],

            // ── IT - Operating Systems ────────────────────────────────────────
            ['body' => 'What operating system technique rapidly switches a CPU between multiple processes to simulate parallel execution?', 'correct_answer' => 'context switching', 'category' => 'IT - Operating Systems'],
            ['body' => 'What area of memory keeps track of a program\'s function calls, local variables, and return addresses?', 'correct_answer' => 'the call stack', 'category' => 'IT - Operating Systems'],
            ['body' => 'What memory management technique lets programs use more address space than the physical RAM installed?', 'correct_answer' => 'virtual memory', 'category' => 'IT - Operating Systems'],
            ['body' => 'What operating system component directly manages hardware and mediates every system call from programs?', 'correct_answer' => 'the kernel', 'category' => 'IT - Operating Systems'],
            ['body' => 'What term describes a situation where two or more processes are stuck permanently waiting on each other\'s held resources?', 'correct_answer' => 'a deadlock', 'category' => 'IT - Operating Systems'],
            ['body' => 'What scheduling algorithm gives each process a fixed time slice before cycling to the next process in line?', 'correct_answer' => 'round robin scheduling', 'category' => 'IT - Operating Systems'],
            ['body' => 'What disk area temporarily stores memory pages that no longer fit in physical RAM?', 'correct_answer' => 'swap space', 'category' => 'IT - Operating Systems'],
            ['body' => 'What firmware standard replaced the legacy BIOS to initialize hardware before booting an operating system?', 'correct_answer' => 'unified extensible firmware interface', 'category' => 'IT - Operating Systems'],
            ['body' => 'What type of operating system guarantees that tasks complete within strict, predictable deadlines?', 'correct_answer' => 'real time operating system', 'category' => 'IT - Operating Systems'],
            ['body' => 'What Unix mechanism connects the output of one command directly into the input of another?', 'correct_answer' => 'a pipe', 'category' => 'IT - Operating Systems'],

            // ── IT - Computer History ─────────────────────────────────────────
            ['body' => 'Who is widely credited as the first computer programmer, for her work on Charles Babbage\'s Analytical Engine?', 'correct_answer' => 'ada lovelace', 'category' => 'IT - Computer History'],
            ['body' => 'What does the acronym ENIAC, the first general-purpose electronic computer, stand for?', 'correct_answer' => 'electronic numerical integrator and computer', 'category' => 'IT - Computer History'],
            ['body' => 'What British mathematician is considered the father of theoretical computer science and helped crack the Enigma cipher?', 'correct_answer' => 'alan turing', 'category' => 'IT - Computer History'],
            ['body' => 'What is the name of the thought experiment Alan Turing proposed to test a machine\'s ability to exhibit intelligent behavior?', 'correct_answer' => 'the turing test', 'category' => 'IT - Computer History'],
            ['body' => 'What company did Steve Jobs and Steve Wozniak found in a garage in 1976?', 'correct_answer' => 'apple computer', 'category' => 'IT - Computer History'],
            ['body' => 'What was the first commercially successful graphical web browser, released in 1993?', 'correct_answer' => 'mosaic browser', 'category' => 'IT - Computer History'],
            ['body' => 'What operating system kernel did Linus Torvalds begin developing as a student project in 1991?', 'correct_answer' => 'linux kernel', 'category' => 'IT - Computer History'],
            ['body' => 'What was the name of the worm that in 1988 became one of the first to spread widely across the early internet?', 'correct_answer' => 'the morris worm', 'category' => 'IT - Computer History'],
            ['body' => 'What does the acronym ARPANET, the precursor to the modern internet, stand for?', 'correct_answer' => 'advanced research projects agency network', 'category' => 'IT - Computer History'],
            ['body' => 'What programming language, created by Dennis Ritchie in the early 1970s, underlies Unix and influenced countless later languages?', 'correct_answer' => 'the c programming language', 'category' => 'IT - Computer History'],

            // ── IT - Algorithms & Data Structures ─────────────────────────────
            ['body' => 'What sorting algorithm repeatedly divides a list in half, sorts each half, and merges the results?', 'correct_answer' => 'merge sort', 'category' => 'IT - Algorithms'],
            ['body' => 'What data structure retrieves the most recently added item first, following a "last in, first out" rule?', 'correct_answer' => 'a stack', 'category' => 'IT - Algorithms'],
            ['body' => 'What data structure retrieves items in the order they were added, following a "first in, first out" rule?', 'correct_answer' => 'a queue', 'category' => 'IT - Algorithms'],
            ['body' => 'What search algorithm repeatedly halves a sorted list to find a target value?', 'correct_answer' => 'binary search', 'category' => 'IT - Algorithms'],
            ['body' => 'What graph traversal algorithm explores as far as possible along one branch before backtracking?', 'correct_answer' => 'depth first search', 'category' => 'IT - Algorithms'],
            ['body' => 'What graph traversal algorithm explores all neighbors at the current depth before moving deeper?', 'correct_answer' => 'breadth first search', 'category' => 'IT - Algorithms'],
            ['body' => 'What algorithm, named after computer scientist Edsger Dijkstra, finds the shortest path between nodes in a weighted graph?', 'correct_answer' => 'dijkstras algorithm', 'category' => 'IT - Algorithms'],
            ['body' => 'What term describes an algorithm\'s efficiency expressed as its worst-case growth rate relative to input size?', 'correct_answer' => 'big o notation', 'category' => 'IT - Algorithms'],
            ['body' => 'What tree-based data structure keeps each parent node smaller (or larger) than its children, enabling fast min or max retrieval?', 'correct_answer' => 'a binary heap', 'category' => 'IT - Algorithms'],
            ['body' => 'What technique solves complex problems by breaking them into overlapping subproblems and storing previously computed results?', 'correct_answer' => 'dynamic programming', 'category' => 'IT - Algorithms'],

            // ── IT - Hardware & Architecture ───────────────────────────────────
            ['body' => 'What computer component performs arithmetic and logic operations at the heart of every instruction executed?', 'correct_answer' => 'the arithmetic logic unit', 'category' => 'IT - Hardware'],
            ['body' => 'What type of memory is wiped clean every time a computer loses power?', 'correct_answer' => 'volatile memory', 'category' => 'IT - Hardware'],
            ['body' => 'What storage technology uses flash memory chips instead of spinning magnetic platters?', 'correct_answer' => 'solid state drive', 'category' => 'IT - Hardware'],
            ['body' => 'What computing architecture principle stores both program instructions and data in the same memory space?', 'correct_answer' => 'von neumann architecture', 'category' => 'IT - Hardware'],
            ['body' => 'What term describes cramming more transistors onto integrated circuits, roughly doubling the count every two years?', 'correct_answer' => 'moores law', 'category' => 'IT - Hardware'],
            ['body' => 'What small, extremely fast memory located directly on or near the CPU stores frequently used data to speed up processing?', 'correct_answer' => 'cpu cache', 'category' => 'IT - Hardware'],
            ['body' => 'What computing paradigm distributes processing across servers located physically close to where data is generated, reducing latency?', 'correct_answer' => 'edge computing', 'category' => 'IT - Hardware'],
            ['body' => 'What term describes running multiple operating systems on one physical machine using isolated virtual environments?', 'correct_answer' => 'virtual machines', 'category' => 'IT - Hardware'],
            ['body' => 'What type of processor architecture uses a small, highly optimized set of simple instructions to boost efficiency?', 'correct_answer' => 'reduced instruction set computer', 'category' => 'IT - Hardware'],
            ['body' => 'What hardware component converts alternating current from a wall outlet into the direct current a computer\'s components need?', 'correct_answer' => 'a power supply unit', 'category' => 'IT - Hardware'],

            // ── IT - Software Engineering ──────────────────────────────────────
            ['body' => 'What practice automatically builds and tests code every time changes are merged into a shared repository?', 'correct_answer' => 'continuous integration', 'category' => 'IT - Software Engineering'],
            ['body' => 'What practice automatically deploys code to production once it passes all required tests?', 'correct_answer' => 'continuous deployment', 'category' => 'IT - Software Engineering'],
            ['body' => 'What software development methodology emphasizes short, iterative development cycles called sprints?', 'correct_answer' => 'scrum methodology', 'category' => 'IT - Software Engineering'],
            ['body' => 'What document outlines the intended features and behavior of a software system before development begins?', 'correct_answer' => 'a requirements specification', 'category' => 'IT - Software Engineering'],
            ['body' => 'What testing level verifies that individual, isolated pieces of code function correctly on their own?', 'correct_answer' => 'unit testing', 'category' => 'IT - Software Engineering'],
            ['body' => 'What testing level verifies that multiple independently developed modules work correctly together?', 'correct_answer' => 'integration testing', 'category' => 'IT - Software Engineering'],
            ['body' => 'What architectural style exposes application functionality over HTTP using stateless, resource-based endpoints?', 'correct_answer' => 'representational state transfer', 'category' => 'IT - Software Engineering'],
            ['body' => 'What software packaging technique bundles an application with all its dependencies into a portable, isolated unit?', 'correct_answer' => 'containerization', 'category' => 'IT - Software Engineering'],
            ['body' => 'What term describes technical shortcuts taken during development that create future maintenance costs?', 'correct_answer' => 'technical debt', 'category' => 'IT - Software Engineering'],
            ['body' => 'What practice has developers review each other\'s code changes before merging them into the main branch?', 'correct_answer' => 'code review', 'category' => 'IT - Software Engineering'],

            // ── IT - Web & Internet ────────────────────────────────────────────
            ['body' => 'What markup language provides the basic structural skeleton of nearly every web page?', 'correct_answer' => 'hypertext markup language', 'category' => 'IT - Web'],
            ['body' => 'What stylesheet language controls the visual presentation and layout of HTML documents?', 'correct_answer' => 'cascading style sheets', 'category' => 'IT - Web'],
            ['body' => 'What lightweight, human-readable data format, derived from JavaScript object syntax, is widely used for web APIs?', 'correct_answer' => 'javascript object notation', 'category' => 'IT - Web'],
            ['body' => 'What internet protocol delivers email messages from a client to a mail server for sending?', 'correct_answer' => 'simple mail transfer protocol', 'category' => 'IT - Web'],
            ['body' => 'What term describes storing frequently accessed web content on distributed servers closer to users to reduce load times?', 'correct_answer' => 'content delivery network', 'category' => 'IT - Web'],
            ['body' => 'What browser storage mechanism keeps small pieces of data on a user\'s device to track sessions or preferences?', 'correct_answer' => 'http cookies', 'category' => 'IT - Web'],
            ['body' => 'What web technique lets a browser update page content without reloading the entire page, popularized in the mid-2000s?', 'correct_answer' => 'asynchronous javascript and xml', 'category' => 'IT - Web'],
            ['body' => 'What security policy restricts webpages from making requests to a different domain than the one that served them?', 'correct_answer' => 'same origin policy', 'category' => 'IT - Web'],
            ['body' => 'What term describes a website that dynamically adapts its layout to fit different screen sizes and devices?', 'correct_answer' => 'responsive web design', 'category' => 'IT - Web'],
            ['body' => 'What web technology enables a persistent, two-way connection between browser and server for real-time data exchange?', 'correct_answer' => 'websocket protocol', 'category' => 'IT - Web'],

        ];

        foreach ($questions as $q) {
            Question::firstOrCreate(['body' => $q['body']], $q);
        }

        $this->command->info('Seeded ' . count($questions) . ' questions.');
    }
}
